### ISSUE TITLE
[1.12.2 and ¿1.14.4?]Suggestion: exp based on the exp base of the mob

### ISSUE THREAD

**Issue by jalu97** [RobertSkalko/Mine-and-Slash#100]
I have this mod and others that add mobs, like ice and fire. Some mobs are very stronger to kill but they are not rewarding to kill, just give the same exp and loot like the others. So I'm wondering if there is a way to do that possible

**Comment by RobertSkalko** [comment]
in 1.14.4 there are mob configs in the mine and slash config folder.
