### ISSUE TITLE
[1.14.4] Suggestion: Bosses and Elite

### ISSUE THREAD

**Issue by jalu97** [RobertSkalko/Mine-and-Slash#102]
I suggest to have a bar that fills killing mobs on the maps, and when it fills it summon a boss, a stronger version of a mob with maybe some traits. The other suggestion is to add affixes to some elites mobs, affixes like diablo or poe, for example: reflect some damage, lifesteal, its faster,etc

**Comment by RobertSkalko** [comment]
mobs already have affixes. they are the icons near their name. I am also already planning to add bosses and elites.

**Comment by RobertSkalko** [comment]
bosses implemented in 1.15.2
