### ISSUE TITLE
[1.12.2]Axes and Staffs ignore config

### ISSUE THREAD

**Issue by GeckGlobal** [RobertSkalko/Mine-and-Slash#105]
Currently the mods Axes and staffs deal both vanilla and mod damage regardless off the config setting to disable that. Bows Hammers and Swords work fine. The same is also true for the CompatibleItems.txt

**Comment by AzureZhen** [comment]
Please make an issue here https://github.com/AzureZhen/Mine-and-Slash/issues I handle all 1.12.2 issues there

**Comment by GeckGlobal** [comment]
I will close this issue here.
