### ISSUE TITLE
[1.14.4] MAXIMUM_WORN_RUNED_ITEMS 

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [RobertSkalko/Mine-and-Slash#108]
forge 28.1.86
mmorpg 2.9.3

changing the MAXIMUM_WORN_RUNED_ITEMS in mmorpg-common.toml doesn't have any effect. A value of 10 for that setting produces '[CHAT] Gear Stats Not Added, reason: you are wearing too many runed items! Maximum Possible Unique items (excluding weapon): 3' while wearing 2 runed items (bracelet & charm) plus a runed (empty rune sockets) SilentGear sword, which should've been ignored?

**Comment by RobertSkalko** [comment]
Make sure you changed it on the server.

**Comment by Rumpelstiltskinny** [comment]
I most certainly did. Even restarted it & client. Oddly enough, when I change max runed items setting it stops spamming chat. If I the alter another setting, ie energy per lvl, it resumes spamming about runed items. Acting as if only one or the other setting may be active at a time. Really got me scratching my head. Any ideas?

**Comment by RobertSkalko** [comment]
idk, did that happen on older version?

**Comment by Rumpelstiltskinny** [comment]
Not that I was aware of. Was using 2.8.18 previously and only attempted to alter the config to balance energy regen due to the changes in 2.9+

**Comment by RobertSkalko** [comment]
Hm, i think this is cus configs aren't synced from server to client. Try setting config on both client and server

**Comment by RobertSkalko** [comment]
I assume that fixed it, i'll have to work on configs being syncable
