### ISSUE TITLE
[1.14.4] Suggestion: Tamed Pets Progress with Player (Owner)

### ISSUE THREAD

**Issue by Wisecompany** [RobertSkalko/Mine-and-Slash#109]
Currently, when a pet becomes tamed, their initial level is determined by either:

- Distance from World Spawn (using default config)
- Nearest Player Level (if config is set)

**I suggest making two changes:**

- Always use player (owner) level for Initial Level of tamed pets. **IE:** Player Level 36 = Pet Level 36
- Enable level progression with the player (owner). **IE:** Player Levels Up = Pets Level Up

These changes will help our pets survive as we explore further into our worlds and level up. If you really wanted to go all out, a talent tree for pets would be fantastic.

**Comment by RobertSkalko** [comment]
No. I do not want to focus on pets. But if you want you can use certain items that raise their lvl and even rarity.
