### ISSUE TITLE
[1.14.4] Suggestion: Exploration Options

### ISSUE THREAD

**Issue by Wisecompany** [RobertSkalko/Mine-and-Slash#110]
The default config in Mine & Slash greatly encourages continued exploration. However, Vanilla Minecraft has a lot of features that discourage it. For example, if I spend hours building a base, it really makes me not want to venture further and further away from it to reach mobs my level.

**I've come up with two possible solutions to this issue:**

- A Unique Item that allows teleportation. I'm thinking something along the lines of the Waystones Mod, with stationary teleportation locations (craftable) and a stone to keep in your inventory to use on the go.
- Some kind of mobile base. With campfires in 1.14.4, an adventure bag would be a good fit. It could be upgraded with a campfire, storage options, crafting/smelting, etc. 

Let me know what you think!

**Comment by RobertSkalko** [comment]
adventure maps already exist, same with a config option to scale mob lvl to player. I just need to improve adventure maps more.

**Comment by RobertSkalko** [comment]
I improved adventure maps and i don't think i'll make anything you suggested any time soon so i'm closing the issue. I wish github had a separate issue and suggestion pages..
