### ISSUE TITLE
[1.14.4] Suggestion: Too Many Hotkeys

### ISSUE THREAD

**Issue by Wisecompany** [RobertSkalko/Mine-and-Slash#111]
- J - Talent Tree
- O - Stat Point Allocation
- P - Player Stats

Why not have a single hotkey (P for Player) with a tabbed interface?

**Comment by MrLittle12** [comment]
I love this idea! This would make browsing my character stats a lot easier.

**Comment by RobertSkalko** [comment]
implemented in 1.15.2
