### ISSUE TITLE
1.14.4 Silent's Gear doesn't Scale

### ISSUE THREAD

**Issue by kreezxil** [RobertSkalko/Mine-and-Slash#112]
The custom armors you can make from blueprints from the Silent Gear mod do not scale, though weapons do. Not sure if a bug or not, but since weapons scale, it's logical to conclude armors should too.

Originally open on my pack World of Dragons - A New Age at https://github.com/kreezxil/World-of-Dragons-A-New-Age/issues/9

**Comment by RobertSkalko** [comment]
you should foward this to silent. He included auto compatibility for my mod inside his.
