### ISSUE TITLE
World Fails to Open

### ISSUE THREAD

**Issue by WenXin20** [RobertSkalko/Mine-and-Slash#113]
`Minecraft v1.14.4`
`Forge v28.1.90`
`Mine & Slash v1.9.4`

After adding Mine and Slash to a world that previously didn't have it installed, it fails to load. It does not crash, but it freezes once the world loading reaches 100%. The log also shows an error starting at `[10:46:18]`
[Log](https://gist.github.com/WenXin20/0334e0123ab027af530347e66d47a0cd)

**Comment by RobertSkalko** [comment]
try using v2.9.3

**Comment by WenXin20** [comment]
Oops, I meant to put that I was using v2.9.4 but I'll try that version to be sure.

**Comment by WenXin20** [comment]
I still get the same error with v2.9.3

**Comment by RobertSkalko** [comment]
try removing my mod and see if it still fails to load. if it works fine, then try re-adding my mod and posting the full log

**Comment by WenXin20** [comment]
Yes, that is what I have already done and have already posted the full log above.

GitHub might have truncated the file, just click on the link at the top of the file to see the full log.

**Comment by WenXin20** [comment]
I haven't had a problem running Mine & Slash for a while now, so I'll go ahead and close this.
