### ISSUE TITLE
Wand/staff causing server crash

### ISSUE THREAD

**Issue by 3dguru** [RobertSkalko/Mine-and-Slash#116]
Server crashes when 2 players in different chunks use staff or wand ... see logs

[crash-2019-11-19_22.07.47-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/3867287/crash-2019-11-19_22.07.47-server.txt)
[latest.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3867288/latest.log)

**Comment by RobertSkalko** [comment]
did update fix this?

**Comment by RobertSkalko** [comment]
reopen if 1.15.2 update didn't fix this.
