### ISSUE TITLE
Allow Waterlogging of Blocks

### ISSUE THREAD

**Issue by WenXin20** [RobertSkalko/Mine-and-Slash#117]
Minecraft v1.14.4

- Waterlogging could be added for the Loot Crate, the Alchemy Station, the Gear Modify & Salvage Stations, and the Gear Craft & Repair Stations.
- The Tinkering Station & Map Device renders incorrectly underwater, it displays water flowing down it's sides.

**Comment by RobertSkalko** [comment]
Not looking to do these things.
