### ISSUE TITLE
[1.14.4 2.9.3] MAX ENTITY LEVEL being ignored

### ISSUE THREAD

**Issue by kreezxil** [RobertSkalko/Mine-and-Slash#118]
For quite some time I've had the max entity level set to 1000 however my players have just informed me that no matter how far out they go on the server the mobs never go above 100.

Config | Paste
---- | ----
ModEntityConfigs.txt | http://paste.ubuntu.com/p/66yJBZFTv8/

**Comment by AzureZhen** [comment]
Found your issue. You didn't update the DimensionConfigs as well. 
`
{
  "version": "1.0",
  "ConfigType": "dimensions_config",
  "defaultconfig": {
    "MOB_LEVEL_PER_DISTANCE": 125,
    "MOB_LEVEL_ONE_AREA": 50,
    "MAXIMUM_MOB_LEVEL": 100,
    "MINIMUM_MOB_LEVEL": 1,
    "LEVEL_FOR_MOBS_TO_BE_LEGENDARY": 10,
    "LEVEL_FOR_MOBS_TO_BE_MYTHICAL": 20,
    "SCALE_MOB_LEVEL_TO_NEAREST_PLAYER": false,
    "DROPS_UNIQUE_ITEMS": false,
    "MAP_TIER": 0,
    "DROP_MULTIPLIER": 1.0,
    "MOB_STRENGTH_MULTIPLIER": 1.0
  },
  "dimensionsList": {
    "minecraft:overworld": {
      "MOB_LEVEL_PER_DISTANCE": 125,
      "MOB_LEVEL_ONE_AREA": 50,
      "MAXIMUM_MOB_LEVEL": 100,
      "MINIMUM_MOB_LEVEL": 1,
      "LEVEL_FOR_MOBS_TO_BE_LEGENDARY": 10,
      "LEVEL_FOR_MOBS_TO_BE_MYTHICAL": 20,
      "SCALE_MOB_LEVEL_TO_NEAREST_PLAYER": false,
      "DROPS_UNIQUE_ITEMS": false,
      "MAP_TIER": 0,
      "DROP_MULTIPLIER": 1.0,
      "MOB_STRENGTH_MULTIPLIER": 1.0
    },
    "minecraft:the_nether": {
      "MOB_LEVEL_PER_DISTANCE": 75,
      "MOB_LEVEL_ONE_AREA": 100,
      "MAXIMUM_MOB_LEVEL": 100,
      "MINIMUM_MOB_LEVEL": 10,
      "LEVEL_FOR_MOBS_TO_BE_LEGENDARY": 10,
      "LEVEL_FOR_MOBS_TO_BE_MYTHICAL": 20,
      "SCALE_MOB_LEVEL_TO_NEAREST_PLAYER": false,
      "DROPS_UNIQUE_ITEMS": false,
      "MAP_TIER": 0,
      "DROP_MULTIPLIER": 1.0,
      "MOB_STRENGTH_MULTIPLIER": 1.0
    },
    "minecraft:the_end": {
      "MOB_LEVEL_PER_DISTANCE": 125,
      "MOB_LEVEL_ONE_AREA": 50,
      "MAXIMUM_MOB_LEVEL": 100,
      "MINIMUM_MOB_LEVEL": 25,
      "LEVEL_FOR_MOBS_TO_BE_LEGENDARY": 10,
      "LEVEL_FOR_MOBS_TO_BE_MYTHICAL": 20,
      "SCALE_MOB_LEVEL_TO_NEAREST_PLAYER": false,
      "DROPS_UNIQUE_ITEMS": false,
      "MAP_TIER": 0,
      "DROP_MULTIPLIER": 1.0,
      "MOB_STRENGTH_MULTIPLIER": 1.0
    }
  }
}
`

**Comment by kreezxil** [comment]
hah, didn't know I needed to do that too. It was not clear. Thanks for discovering it.
