### ISSUE TITLE
[1.14.4]  Suggestion:  Config option to rename the tiered mobs

### ISSUE THREAD

**Issue by DoragonKeiyou** [RobertSkalko/Mine-and-Slash#122]
Instead of having them generate as "common zombie", "rare zombie", etc., you could have an option in the config that allows you to name them what you want.  So if you wanted them to instead be called "weak zombie" or "elite zombie", a simple commonName = "Common", rareName = "Rare", etc. where anyone could replace "common" with whatever they wanted would show up in game.

**Comment by RobertSkalko** [comment]
implemented in latest 1.15 update
