### ISSUE TITLE
[1.14.4] Bags should ignore renamed items

### ISSUE THREAD

**Issue by bluebear94** [RobertSkalko/Mine-and-Slash#130]
At least [one mod](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs) gives some mobs the ability to cause players to drop their wielded items, and there's always the possibility of accidentally pressing Q with your sword in hand. It's a bit annoying to have to open your bag to get your weapon back once you pick it up. I think having bags ignore named (by anvil) items would be a nice QoL change.

**Comment by RobertSkalko** [comment]
good idea, i can also make enchanted items not be auto put into bags, after all it's more common to enchant than it is to rename your gear

**Comment by RobertSkalko** [comment]
implemented in 1.15.2
