### ISSUE TITLE
[1.14.4]Item Combining Question

### ISSUE THREAD

**Issue by ChiKitsune** [RobertSkalko/Mine-and-Slash#131]
For Mine and Slash-1.14.4-2.9.4
I noticed that if combine two of the same item and rarity there are two groups that then lose all of the Mine and Slash stats on the item and I was wondering if it was intentional.
It is if combine any Spells or if combine mythical gear items it will always lose all of the stats and can no longer be used in any of the station blocks.
It also shows that the item only has one NBT tag instead of Two.
Before crafting them together it also doesn't have the "Compatible Mine and Slash Item" on the result item.

Is that expected to happen?

**Comment by RobertSkalko** [comment]
Yes. but there's a config ONLY_REPAIR_IN_STATION which disables that. Makes the items non repairable (by normal minecraft means), which disables craft grid repair too. But still allows repair at the station, the intended mechanic.

It's cus compatible items are created by checking if the item nbt is clear on inventory open. Craft grid repairing clears nbt.. Meaning with the option disabled you can kind of have twice the chances of getting better items.

I might change the default config value to true in later updates.

**Comment by ChiKitsune** [comment]
Okay thanks I was mainly just checking if it was purposely done.
I do know that doing the normal minecraft repair has helped since after repairing treats as a whole new item and does the current player's level. It meant lower level high rarity items had more of a chance to be reused later.
I can see if you want the Currency items to play a bigger part earlier on, to use the Crafting Station more, or more focused on getting new drops instead for changing which way the config defaults

**Comment by RobertSkalko** [comment]
Yeah items are not supposed to do that at all. But it's the current limitation of compatible items system.

Specifically, there's stuff like autocrafting that doesn't need a player, so even if i hooked to oncraftedevent i still couldn't do it. UNLESS i was to remove the feature of gear scaling to player level. Then compatible items would be compeltely random in their lvl range.
