### ISSUE TITLE
Advancements Crash

### ISSUE THREAD

**Issue by WenXin20** [RobertSkalko/Mine-and-Slash#133]
`Minecraft v1.14.4`
`Forge v28.1.116`
`Mine & Slash v2.9.4`

I'm not entirely sure if this crash is caused by Mine and Slash because I've seen this crash multiple times before but could not find a clear indication of what mod could cause it, but this time I noticed that the mentioned Mine and Slash Advancements right before crashing. It always crashes on world load. 
To fix the crash, I have to delete the advancements folder in the saves directory, but the crash comes back up eventually.

[Crash Report](https://gist.github.com/WenXin20/e915ea47801bc51f956a4fb565dc1f70)
[Full Log](https://gist.github.com/WenXin20/1f4c3f355a7cae280292e5c14d59ff4d) (`[19:41:12]` is when it first errors)

**Comment by RobertSkalko** [comment]
First time seing this. You can try removing my mod and loading again.

**Comment by RobertSkalko** [comment]
seems fixed?
