### ISSUE TITLE
[1.14.4] mmorpg.chat.has_died_by_the_hands_of should use %s for the arguments

### ISSUE THREAD

**Issue by bluebear94** [RobertSkalko/Mine-and-Slash#134]
Currently, it [doesn't](https://github.com/RobertSkalko/Mine-and-Slash/blob/1.15/src/main/resources/assets/mmorpg/lang/en_us.json#L1273), forcing the name of the victim to be displayed at the beginning and the name of the killer at the end. Other languages might have one or both of these in a different position. The string should be changed to use `%s` arguments as with vanilla death messages, with `MyDamageSource#getDeathMessage()` modified to pass the victim and killer as arguments to the text.

**Comment by RobertSkalko** [comment]
Now that i look at it, i dont remember why i overrided the death message at all?

**Comment by RobertSkalko** [comment]
changed to vanilla
