### ISSUE TITLE
[1.1.2.2-1.9.2] Issue with Level Display

### ISSUE THREAD

**Issue by kreezxil** [RobertSkalko/Mine-and-Slash#139]
Was testing levels by giving myself enormous amounts of exp via /givexp. Discovered that  M&S doesn't recalculate the level or autoadvance you if you gain more than a level in xp via this operation.

![image](https://user-images.githubusercontent.com/3880072/74345676-10b40600-4d74-11ea-9ddb-51ef334c56c3.png)

Is there anyway to force it to recalculate the levels when one recieves a ton of xp via the /givexp command?

**Comment by RobertSkalko** [comment]
Give urself 1 xp 100 times

**Comment by kreezxil** [comment]
oy vey
