### ISSUE TITLE
[1.12.2]Suggestion：To make it into a difficulty ascending module

### ISSUE THREAD

**Issue by Abo233** [RobertSkalko/Mine-and-Slash#140]
1. Can you remove all items from the module? 
（Why is that? Because of the correlation is not strong）
  

2.Delete the adventure map  and other buttons（It's no use）

3. Retain only attributes, and UI, and configuration files
   

4.Can eat through ascension magic defense
 （item:Provided by you）Come on...

5.Add a new item called forging machine, in order to give any additional special weapons properties（Improve the correlation）

**Comment by Abo233** [comment]
This module game play is very interesting, there is no need to add so many things

**Comment by Abo233** [comment]
Add some special items to improve properties,

**Comment by Abo233** [comment]
I am a Chinese, can't speak English

**Comment by Abo233** [comment]
I might not be clearly described

**Comment by RobertSkalko** [comment]
I can't understand much but

1.12 won't get updated. Update to newest version (currently 1.15.2)

> 
5.Add a new item called forging machine, in order to give any additional special weapons properties

This is interesting if i understood correctly, i might implement it.

**Comment by AzureDoom** [comment]
So you want to gut the mod? Yeah no, like Robert sad, no more 1.12.2 updates besides serious bug fixes.
