### ISSUE TITLE
[1.12.2] Crash when equipping an amulet

### ISSUE THREAD

**Issue by MechanosG** [RobertSkalko/Mine-and-Slash#144]
I'm not sure if this is a Mine-and-Slash issue or a Bauble issue, or even a conflict with another mod.  But trying to equip this random amulet:
![2020-02-18_16 01 53](https://user-images.githubusercontent.com/4360512/74788946-1031d880-5268-11ea-854f-fb2a28e87906.png)

Causes this crash to happen: [crash-2020-02-18_15.48.55-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/4222425/crash-2020-02-18_15.48.55-server.txt)

VanillaFix allows the game to keep running after the crash, but the bauble inventory completely breaks afterwards.  Clicking empty bauble inventory slots will pick up random items from my regular inventory, as if the slots have become linked.  Eventually it'll crash again clicking these bugged slots.

**Comment by MechanosG** [comment]
Figured I should add, restarting MC made the issue go away.  But it randomly seems to come back.  I've been disabling random inventory mods 1 at a time, to see if they were somehow the cause.  But sometimes everything works with everything enabled, so I'm unsure of how to reproduce the problem.  My closest lead is that it's "possibly" related to QuickerCrafting, but it claims to be baubles compatible.  When the problem first started, I had QuickerCrafting replacing the default inventory open screen..  maybe the problem only shows up when things open in that order?
-few minutes of testing later-

Yep, that's the problem.  QuickerCrafting breaks baubles if you try to open the Baubles menu from the QuickerCrafting menu.  I guess this isn't Mine and slash related, my bad.  Gonna make a report over there.

**Comment by RobertSkalko** [comment]
Alright, closing.
