### ISSUE TITLE
[1.15.2]Gear Salvage Station does not work continuously

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#146]
In Gear Salvage Station, if the same ore given by Rarity, Gears of the same Rarity in Gear Salvage Station cannot work continuously and will stop.

**Comment by RobertSkalko** [comment]
Was the output(right part) of the station full?

**Comment by mcfensi** [comment]
No full, only one space occupied

**Comment by mcfensi** [comment]
This is feedback from Chinese players, and it was true when I tested it, so I came here to give feedback.

For example, if you put 2 Uncommon Gears, you will get 1 Uncommon Ore, and the other Uncommon Gear will not run.

Thank you for making this mod. Chinese players like it very much.

**Comment by RobertSkalko** [comment]
found it, should be fixed
