### ISSUE TITLE
Pressing J doesn't seem to work

### ISSUE THREAD

**Issue by totoshogun** [RobertSkalko/Mine-and-Slash#153]
Hi i just added this mod and the button j doesn't seem to open anything (i did check if the key was already in use and no nothing is using the key j - also under Mine and Slash i only see Current Map stats. Player Stats and What Unique Items current map can drop, nothing about Talent trees) not sure what is causing the problem as everything seems to be working fine just can't open the talent tree...

Also i may i get a list of what is added in version 1.12.2 as i can't seem to find anywhere on what is added and missing.

Using forge minecraft 1.12.2
Mod version: Mine+and+Slash-1.12.2-1.9.3

**Comment by mcfensi** [comment]
1.12.2 does not have these, please use the latest version

**Comment by AzureDoom** [comment]
No bug, update to 1.14.4 or 1.15.2 for these new features. You should be able to close this @RobertSkalko

**Comment by RobertSkalko** [comment]
I didn't catch that thanks.

**Comment by totoshogun** [comment]
> No bug, update to 1.14.4 or 1.15.2 for these new features. You should be able to close this @RobertSkalko

Ah i see, thanks :)  - you should point out what is and isn't in each version so other people may not be confused as i was lol
