### ISSUE TITLE
[1.15.2]Key of new Dawn and Key of Unity bug

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#158]
Key of new Dawn causes the set to disappear instead of rerolling.
Key of Unity cannot add set.

**Comment by RobertSkalko** [comment]
please try new build

**Comment by mcfensi** [comment]
It works now. But I found a new problem, Key of Unity does not work for Weapon with Rune.

**Comment by RobertSkalko** [comment]
works fine for me. weapons though probably dont have a set related to them.

**Comment by mcfensi** [comment]
Ok, just weapons will consume key of unity, which will lead to waste.
