### ISSUE TITLE
Projectile could change angle while jumping

### ISSUE THREAD

**Issue by EndsM** [RobertSkalko/Mine-and-Slash#159]
3.2.3 lead in a new features:bolts now don't feel gravity anylonger.
However, while I trying to fire some snowball while jumping. I got a big problem.
when you are jumping, the bullets you shoot off will change the launch angle with it.
For example, while you jumping up, the angle will changed to obliquely up. Make it flying over your enemy. While you falling down, the angle will obliquely down, make the bullets fall on the ground very soon.
It was a quiet old issues in the game, but this change make it much more serious. Could you trying to make it perform better? please

**Comment by RobertSkalko** [comment]
I'm not sure this is a bug? Seems normal.

**Comment by EndsM** [comment]
well, maybe it just the game's feature. I'm not really sure either. Just it sometimes quite annoying. But it could be fine, I guess.

**Comment by RobertSkalko** [comment]
Alright, give it time to get used to it, if it still feels "off" in a week or so then it might be an issue.
