### ISSUE TITLE
[1.15.2] Server crash - NullPointerException: Ticking entity 	at com.robertx22.mine_and_slash.uncommon.capability.entity.EntityCap

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#165]
Crash report-
https://gist.github.com/ProsperCraft/959d6e37a4c61f8a37b85058a76fa801

latest log-
https://gist.githubusercontent.com/ProsperCraft/0eb625f2be9861b2c5b7052206725b9c/raw/3453d3e09f826595236ce0a74925c8cdc257af7b/gistfile1.txt

Happens randomly, no known way to force it to happen.

**Comment by ProsperCraft** [comment]
Another one - https://gist.github.com/ProsperCraft/3c4e245def901dfd474f0fb91ef93e2c

**Comment by RobertSkalko** [comment]
i think some1 already reported me this and i fixed it in dev, but im in the process of a bigish update so can't hotfix right now

**Comment by RobertSkalko** [comment]
should be fixed
