### ISSUE TITLE
[1.15.2] Server Crash- java.lang.IllegalArgumentException: bound must be positive 	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_242] {} 	at com.robertx22.mine_and_slash.uncommon.utilityclasses.RandomUtils.RandomRange

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#166]
Mine and Slash-1.15.2-3.3.0

Crash log - 
https://gist.github.com/ProsperCraft/2b8cb63f02b1c4a8ff92a99c041d514a

[debug.log](https://github.com/RobertSkalko/Mine-and-Slash/files/4326147/debug.log)
[latest.log](https://github.com/RobertSkalko/Mine-and-Slash/files/4326148/latest.log)

**Comment by ProsperCraft** [comment]
[crash-2020-03-12_12.59.15-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/4326352/crash-2020-03-12_12.59.15-server.txt)
[crash-2020-03-12_13.00.17-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/4326353/crash-2020-03-12_13.00.17-server.txt)
[crash-2020-03-12_13.03.35-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/4326354/crash-2020-03-12_13.03.35-server.txt)
[crash-2020-03-12_12.44.12-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/4326355/crash-2020-03-12_12.44.12-server.txt)
[crash-2020-03-12_12.47.52-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/4326356/crash-2020-03-12_12.47.52-server.txt)
[crash-2020-03-12_12.53.31-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/4326357/crash-2020-03-12_12.53.31-server.txt)

**Comment by RobertSkalko** [comment]
gimme a sec

**Comment by RobertSkalko** [comment]
pushing update

**Comment by RobertSkalko** [comment]
going to sleep soon so hopefully no more crashes
