### ISSUE TITLE
[1.15.2]Door and Monster BUG

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#169]
Keep the monsters out of the door and use ranged weapons, such as bows to damage the monsters outside the door.

**Comment by RobertSkalko** [comment]
doesnt sound like a bug, more like a design problem? I guess i can try making mobs able to open doors.

**Comment by mcfensi** [comment]
It ’s also a way, otherwise it ’s not too fair to melee professions.

**Comment by RobertSkalko** [comment]
Closing, i added a way for mobs to open doors but doesn't work perfectly. As this is more of a suggestion than a bug, open again if you're a programmer and know a way to improve my solution.
