### ISSUE TITLE
[1.15.2] Master bag salvage being far too generous - bug

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#172]
A player on the server reported this, they said they only have a common quality salvage bag, and have not really killed that much stuff, and have all of these things.

![unknown (17)](https://user-images.githubusercontent.com/4427684/76704125-7a3d7200-669c-11ea-87d2-e49250dc3506.png)

**Comment by RobertSkalko** [comment]
hm, maybe they were taking the map chests?

**Comment by ProsperCraft** [comment]
He did, 4-5 of them he said, is there really that much loot in them?

**Comment by RobertSkalko** [comment]
I have 1 idea. It's possible he had some mythic ores. But bought stuff from a trader and the trader gave him a lot of change in legendary ores.

**Comment by RobertSkalko** [comment]
Tell me again if this happens to more than 1 player. Currently i don't have even an assumption for why it could happen.

**Comment by RobertSkalko** [comment]
as nobody else reported anything like this, it was either fixed or a user error. Or maybe it was from before i nerfed the loot in dungeons.
