### ISSUE TITLE
[1.15.2]Right click on Master Bag in Offhand and disappear

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#176]
If there is an item in the main hand, when the right hand of Offhand causes the Master Bag to disappear, Offhand will copy the item of the main hand.

Known bug exists in 1.14.4 / 1.15.2, I don't know 1.12.2.

**Comment by RobertSkalko** [comment]
will be fixed

**Comment by mcfensi** [comment]
3.4.0 already fixed
