### ISSUE TITLE
Rune Issue

### ISSUE THREAD

**Issue by Onikage056** [RobertSkalko/Mine-and-Slash#178]
This is less an issue in the conventional sense, and more a lack of foresight on your part... There is absolutely nothing indicating how to add a rune to a Runed item, or if there are any restrictions to adding runes. There's just rune sockets, runes, and a runeword awakener.

**Comment by RobertSkalko** [comment]
Nothing? It literally says on the rune that it can be used in the modify station. And if you put it in and it doesn't work, it tells you why it doesn't work. 

Are these not enough or you didn't find them somehow?

**Comment by Onikage056** [comment]
First, it says, on the Runeword Awakener, "Use in the ITEM Modify Station," not GEAR Modify Station. Bit misleading there... second, I've tried using the Awakener on several items, both part of the mod and not, to no effect. The Modify station doesn't progress at all.

**Comment by RobertSkalko** [comment]
What version are you on? The awaken item should have requirements and one of requirements is "matching runes are in gear".

I'll rename gear modify to just modify station, as its used for modifying other things too.

**Comment by Onikage056** [comment]
Okay, I see what happened...
My apologies. I was experimenting in creative mode when trying the rune system out.
I just got a Common rune in Survival that has stats on it... the creative-spawned runes were blank.
Even so, it appears the awakener doesn't work on Mine and Slash compatible Techguns.

That said... Mine and Slash 1.9.3
I'm using the Kreezcraft's World of Dragons mod pack (Minecraft 1.12.2.)

**Comment by RobertSkalko** [comment]
Pretty sure it works. And yeah items with random stats can't be spawned like that, you have to use commands. This is much easier in 1.15 now as commands have suggestions.

Oh and that makes sense, items like that spawned in creative dont have tooltips probably.

Just insert the runes and when you have enough for a combo, add the awaken item.
