### ISSUE TITLE
[1.15.2]3.4.0Equipment name color

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#180]
The color of the new item names is not uniform. For example, the epic prefix is purple, and the name and suffix are blue.

**Comment by RobertSkalko** [comment]
this should be only true for old items. if new items come like that, it's a bug.

**Comment by mcfensi** [comment]
Yes i created a new world

**Comment by RobertSkalko** [comment]
what items are the problem then?

**Comment by RobertSkalko** [comment]
oh, could be just the chinese translation

**Comment by mcfensi** [comment]
It turned out to be this way, I know, thank you, I am going to modify it.
