### ISSUE TITLE
Trying Elemental Water Ranger can't get any elemental bonus

### ISSUE THREAD

**Issue by 2001plee** [RobertSkalko/Mine-and-Slash#183]
So I'm trying elemental Ranger and I put myself at 60 to test it out and put the stats in right side for ranger and speed to the top for the water buffs like 12% all water damage, 5% water damage for weapons, and  5% water spell to atk damage in the talent tree. In the spell tree, I got the 3 5% water All damage buffs for spells and weapons. However, after all, that is done I only get 12% Water spell to  Atk Dmg: 12% in Stat info 0 in water penetration even though I got the 2 5% water penetration.  and my water spell damage is 0. Any ideas?

**Comment by RobertSkalko** [comment]
"0 in water penetration even though I got the 2 5% water penetration"

Your problem is that you missunderstand stat types.  5% more of 0 is 0. You need to actually get the stat elsewhere so it can be increased by that talent.
