### ISSUE TITLE
Side hotbar missing transparency

### ISSUE THREAD

**Issue by WenXin20** [RobertSkalko/Mine-and-Slash#184]
`Minecraft v1.15.2`
`Mine & Slash v3.4.1`

The side hotbar currently does not take transparency into account, despite the texture file having transparent pixels. It should render similar to the normal hotbar.

**Comment by RobertSkalko** [comment]
should be fixed

**Comment by WenXin20** [comment]
It's mostly fixed, but whenever the mob health GUI pops up, the hotbar loses its transparency again.

**Comment by RobertSkalko** [comment]
cant seem to reproduce that
