### ISSUE TITLE
[1.15.2] The health goes to 1

### ISSUE THREAD

**Issue by EnterFor** [RobertSkalko/Mine-and-Slash#185]
![image](https://user-images.githubusercontent.com/10114685/77628351-e3699300-6f82-11ea-8a88-7bf699767803.png)
![image](https://user-images.githubusercontent.com/10114685/77628366-eb293780-6f82-11ea-9d3c-a0e8caac258a.png)
When I learned this talent, my hit point changed to 1
When I reset it:
![image](https://user-images.githubusercontent.com/10114685/77628502-190e7c00-6f83-11ea-8163-7b2dd0923618.png)
Mod：3.4.2

**Comment by RobertSkalko** [comment]
Not a bug, the description literally says it sets the hp to 1.
