### ISSUE TITLE
[1.14.4][2.9.4] Server crash after exploring the world

### ISSUE THREAD

**Issue by Traktool** [RobertSkalko/Mine-and-Slash#188]
I've downloaded "Mine and Slash 1.14.4 2.9.4", but after exploring the world, it crash.
I've tried and tried a lot of configurations, removing some mods etc, and it appears that this version crash the server after exploring a new region (not chunk, but region)

The version 2.9.3 don't crash the server, so if you can solve this crash, thank you so much ! ;)

**Comment by AzureDoom** [comment]
wow 5/7 no crash log means you can't get help.

**Comment by RobertSkalko** [comment]
1.14 is not supported unless azure feels like it. Closing.
