### ISSUE TITLE
Runes without stats

### ISSUE THREAD

**Issue by IwashiPT** [RobertSkalko/Mine-and-Slash#189]
Hello. Sorry to bother but I don't know if this is a bug or what not but some of the Runes I get don't have any stats on them.
I'm linking 2 images of the stated issue, one with a Rune showing stats, and the other not showing.

Without Stats - https://drive.google.com/open?id=1o1Lu9iMivCXx_mPADBYR6vBZHTGobPMF

With Stats - https://drive.google.com/open?id=1ioI2fE43QyCLgD_An0CC4xqK4ewl1F1U

Thanks in advance. Loving the mod :)

**Comment by RobertSkalko** [comment]
probably fixed in 3.5.0.
