### ISSUE TITLE
Missing Shield textures

### ISSUE THREAD

**Issue by Fogrits** [RobertSkalko/Mine-and-Slash#19]
the title explains itself.

[Image](https://i.imgur.com/dT3UrH2.png)

**Comment by RobertSkalko** [comment]
just epic shield has missing texture or do others too?

Hm i think i know what's the problem.

**Comment by Fogrits** [comment]
Every shield is missing their texture

**Comment by RobertSkalko** [comment]
ill release a hotfix for this today

**Comment by RobertSkalko** [comment]
hotfix up, just needs 10 minutes for curse to confirm it.
