### ISSUE TITLE
[1.15.2] No config option to remove spawn inventory items

### ISSUE THREAD

**Issue by Besiegel** [RobertSkalko/Mine-and-Slash#190]
New worlds always start your character with a full set of armor, 2 rings, a bracelet, a necklace, and a sword and there is no option in the config to disable this

**Comment by RobertSkalko** [comment]
its a server config GET_STARTER_ITEMS

**Comment by Besiegel** [comment]
There is no server config - I have launched and played the save. Maybe thats the problem?

**Comment by RobertSkalko** [comment]
"Where are the configs?" > Server configs are located in your world/serverconfig folder. Client configs are in the normal config directory and special configs are in config/Mine and Slash folder

**Comment by Besiegel** [comment]
Wait, so how am I supposed to prevent spawning in with a full inventory if I have to create a world to change that config for each world?

**Comment by RobertSkalko** [comment]
You have a point, i missed that since i transfered the configs. I'll see what to do.

**Comment by Besiegel** [comment]
Should I create a new issue or will you re-open this one?

**Comment by RobertSkalko** [comment]
fixed
