### ISSUE TITLE
[1.15.2] Hardened Zombie with too much HP

### ISSUE THREAD

**Issue by Besiegel** [RobertSkalko/Mine-and-Slash#191]
Boss mobs can sometimes be too strong. I ran into a dungeon with spawners that created many zombies and one of the zombies was a hardened level 4 zombie with over 800 health. This seems like something mightve been broken as the other level 4 hardened zombies were much lower health (200 or less)

**Comment by RobertSkalko** [comment]
pretty sure nothing is broken there. mobs have more hp based on their rarity

**Comment by Besiegel** [comment]
800 HP on a level 4 blue rarity mob doesnt seem right though. My max weapon damage was 10 - thats 80 hits where I do the full damage.

**Comment by RobertSkalko** [comment]
then it's some other mod modifying that mob's health.
