### ISSUE TITLE
[Suggestion] Add config options to control level progression

### ISSUE THREAD

**Issue by lamoyrl90** [RobertSkalko/Mine-and-Slash#193]
First off: I love this mod. It really adds a new depth to character development without feeling hacky or foreign.

That being said, I'd love to have a bit more control over level progression. I'd really like to see config options for per-level XP requirements and stat and skill point rewards at each level. Also: I'm not sure if there's a level cap, but if there is it would be nice to be able to control it. Oh: and maybe some ability to tweak the vanilla-to-M&S item stat conversion. It's kind've opaque right now how the stats actually get calculated for each item.

That's all! Keep up the great work! This mod is a really great way for modern modded Minecraft to get going!

**Comment by AzureDoom** [comment]
> Also: I'm not sure if there's a level cap, but if there is it would be nice to be able to control it.
There is a config option for this

> maybe some ability to tweak the vanilla-to-M&S item stat conversion.
To configure this yourself use a datapack for this if you are 1.15.2, for 1.14.2 and 1.12 you will need to do this by adding the items to the compatibles items file and editing yourself.

**Comment by lamoyrl90** [comment]
> There is a config option for this

Ah, I must have overlooked it. Which file is it in?
 
> To configure this yourself use a datapack for this if you are 1.15.2, for 1.14.2 and 1.12 you will need to do this by adding the items to the compatibles items file and editing yourself.

I guess there's another reason to learn how to use data packs.

**Comment by RobertSkalko** [comment]
its in server config
