### ISSUE TITLE
[1.15.2]Now the bow seems too strong

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#196]
Bow can be released quickly with right click without Attack strength limitation.

Crit + Bleed seems super powerful.

After the mage was weakened, all players in the server played bows.

**Comment by RobertSkalko** [comment]
Hm, but on latest update i should have nerfed both crit and phys damage boosts on the talents.. I'll look into it after the next update as a lot will change, so kinda useless to balance it now.

**Comment by mcfensi** [comment]
Thanks for your hard work!
