### ISSUE TITLE
[1.15.2]Scrabble is missing textures and names

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#198]
Scrabble is missing textures and names.

In addition, will Scrabble support packets in the future to adapt to localization?

**Comment by RobertSkalko** [comment]
No that won't happen. Just english is about 1mb. I assume you mean missing textures when in inventory form, idc as it's not supposed to be craftable or attainable in any way. It wasn't supposed to show in creative though
