### ISSUE TITLE
No limit on secondary attributes?

### ISSUE THREAD

**Issue by Meepedy** [RobertSkalko/Mine-and-Slash#2]
![Screenshot](https://media.discordapp.net/attachments/342499619433086990/543607122324094977/2019-02-08_19.40.15.png?width=720&height=423)

Is this supposed to be allowed?

**Comment by RobertSkalko** [comment]
How did you manage that?

**Comment by RobertSkalko** [comment]
Wow, that was an easy one. The boolean for seeing if item had an attribute added wasn't saved. Thanks for the report, i never would have caught it otherwise!
