### ISSUE TITLE
Staff damage error？

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#20]
Staff left and right keys have double damage, is this a BUG?

Sorry, my English is not very good. I am using Google Translate.

**Comment by RobertSkalko** [comment]
no it's a feature of the staff. just like axes.

The weapons with more energy cost usually have some special thing about them. Ill see what i can do to make this more understandable.

**Comment by mcfensi** [comment]
Ok, I know now, thank you for your reply.
