### ISSUE TITLE
[1.15.2]mmorpg.stat.unknown_stat

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#200]
mmorpg.stat.unknown_stat is displayed on the equipment, it is not displayed correctly

**Comment by RobertSkalko** [comment]
that happens for every stat that is deleted or renamed. the log file should have the exact stat name

**Comment by mcfensi** [comment]
Players say it's the newly acquired equipment in 3.5.1

**Comment by RobertSkalko** [comment]
a log would still be helpful

**Comment by mcfensi** [comment]
Sorry, this is not my server, maybe I can't help
