### ISSUE TITLE
[1.15.2-Mod-3.5.1]Team experience is not Shared

### ISSUE THREAD

**Issue by EnterFor** [RobertSkalko/Mine-and-Slash#201]
I'm as specific as I can be that when my players are in a group, there is no damage to the group, but the experience will not be Shared.
I remember using version 3.4.2 without this problem.
And I type in /slash party list, which always shows me alone.
Other players on my server had the same problem.

The console has no error messages.
Please feel free to contact me if you need any information

**Comment by EnterFor** [comment]
I tried to get the player to drop out of the team and regroup, to no avail

**Comment by Putthelime** [comment]
I am also experiencing this issue.  I do not even see my party member's name under 'party list'.  Invite goes out > player joins > go to list to verify and it only shows self.  Attempt to invite/join, but it says 'already in party'.  There is no shared experience.  

Otherwise, totally awesome mod!

**Comment by AzureDoom** [comment]
This is a known issue and is fixed with the upcoming 3.6.0 spell rework.

**Comment by RobertSkalko** [comment]
should be fixed

**Comment by RobertSkalko** [comment]
closing, make a new issue if exp still isn't shared in newest version
