### ISSUE TITLE
[1.12.2] Gear Repair Station not converting ore to fuel

### ISSUE THREAD

**Issue by Bladesodoom1895** [RobertSkalko/Mine-and-Slash#203]
The gear repair station is not converting any ores into fuel on my server. 

Edit: Not converting vanilla mine craft ores. The gear crafting station does.

**Comment by AzureDoom** [comment]
MC Version?
Mod Version?
Log?

**Comment by Bladesodoom1895** [comment]
MC Version, 1.12.2 forge is the same, Mod version 1.12.2-1.9.3
[2020-04-12-1.log.gz](https://github.com/RobertSkalko/Mine-and-Slash/files/4467309/2020-04-12-1.log.gz)

**Comment by AzureDoom** [comment]
Gear crafting was removed, please try with 1.9.4
