### ISSUE TITLE
hmm bag deletion

### ISSUE THREAD

**Issue by captcookie** [RobertSkalko/Mine-and-Slash#207]
Im wondering if this mod causes other backpacks mod to delete inventory when switching from creative to survival. I read that it does for different bags in this mod e.g. currency bag, gear loot bag, map bag, and master bag, but I have already reported a bug with ignition enderbags not realizing the culprit is most likely this mod. 

https://www.curseforge.com/minecraft/mc-mods/ignition-enderbags 

Either way, Im not sure which mod it is. This is on forge 1.15.2 31.1.46

**Comment by RobertSkalko** [comment]
Well there's a simple way to figure out if my mod is causing the issue. Remove my mod and try it again.
