### ISSUE TITLE
Shields doesn't block projectiles

### ISSUE THREAD

**Issue by Fogrits** [RobertSkalko/Mine-and-Slash#21]
I'm with a shield up and defending, but I'm getting hit as if I weren't with the shield equipped and blocking

**Comment by Fogrits** [comment]
Latest version (the hotfix that you uploaded a while ago - 1.6.12)

**Comment by Fogrits** [comment]
UPDATE: Seems that any previous versions suffer from that problem too.
(Tested from 1.6.0 to latest)

**Comment by RobertSkalko** [comment]
This is normal, shields only block a portion of the damage, if you block all of it, then the attack is canceled and you don't get hit. I'll think how to inform players of this better. I just assumed the block strength stat would be self explainable.

**Comment by Fogrits** [comment]
Oh, so that's why...
Also, regarding shields... Can you make it so your shields stay lower in the screen? the shields eat about 1/5 of my screen just by having it on my offhand

**Comment by RobertSkalko** [comment]
I'll look into that. that's the main reason i dislike shields. I think they should be indentical to vanilla shields tho

**Comment by Fogrits** [comment]
I think that you could do something like completely block the projectile, but dealing 1/4 of the damage it would do to the player

**Comment by Fogrits** [comment]
Thanks in advance :)
