### ISSUE TITLE
Mana Cost Reduction can't find Mana_Cost

### ISSUE THREAD

**Issue by siranthos** [RobertSkalko/Mine-and-Slash#213]
A charm with the affix of mana cost reduction is spamming the console with an error message

java.lang.exception: trying to get non existent value: mana_cost

After like 3 hours of not noticing, the log file was like 2 GB.

Included a log file.

[latest.log](https://github.com/RobertSkalko/Mine-and-Slash/files/4515856/latest.log)

**Comment by RobertSkalko** [comment]
ye that's an oversight, sec.

**Comment by RobertSkalko** [comment]
should be fixed in latest update
