### ISSUE TITLE
Is there a way to make lycanites crafted items compatable with mine and slash? and compatability attempt

### ISSUE THREAD

**Issue by Divinesmiter** [RobertSkalko/Mine-and-Slash#215]
Crafted a weapon using lyconite mob parts and it does not have compatibility for the stats of other normal weapons. So I tried following the wiki to generate a json file, but even though it says it generates files, they are not there nor am I able to search for them and find them. Any help, if it is even possible to do this, would be appreciated.

**Comment by AzureDoom** [comment]
Check in `/config/mine-and-slash/generated` you will then need to take those files and put them into a datapack. You can also try enabling auto compat via the `ServerConfig` located in the world save folder.

**Comment by RobertSkalko** [comment]
Or update to 1.15 and turn on a config option

**Comment by RobertSkalko** [comment]
Tech help questions will all be closed in a day or two. If you have any more problems ask for help on discord.
