### ISSUE TITLE
Listen to others but I have not tested the BUG

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#216]
1.15.2-3.6.7

1. Thunder Spear attack party will cause the server to crash.
2. When the Gear Modify Station is working, others can copy items after they are destroyed.(I found no problem in the LAN test)

**Comment by RobertSkalko** [comment]
Can you elaborate onthe modify station bug?

**Comment by mcfensi** [comment]
His original words were: When he was in the modify equipment, others digging in the modify station, the contents inside did not fall, but there was an extra equipment outside.

This may be a problem with the game mechanics, I know some modules also have this problem. Some plugin authors will fix two problems by prohibiting two players from opening a container at the same time or not destroying the container being used by others.

**Comment by mcfensi** [comment]
He probably found thunder spear Attack teammates after the 3.6.7 update will cause the server to crash. This server is not mine, and I have no way to provide logs.

**Comment by RobertSkalko** [comment]
How exactly was the station relocated? If you just broke the block, there's no way the item could still be inside the block.

**Comment by mcfensi** [comment]
I do n’t know. My own test was to destroy the modify station. The items inside would drop together and would not be stored in it. The result is normal. Sorry, maybe this is not a problem of this mod, please ignore this problem.

**Comment by Dyschromat** [comment]
It's a bug:

When one person has the interface of the Gear Modify Station open while it's working and another person destroys it, both get the items that had been placed in it.
repeated it 5 times, both in surival mode.

Quickfix: Make the Station indestructible while it is in use.

Further: Check other Stations in the modpack if it happens with them too.

**Comment by RobertSkalko** [comment]
I reproduced it and fixed it.

**Comment by RobertSkalko** [comment]
gonna close, if the spear party crash still happens on latest version please open new issue but with a latest log.
