### ISSUE TITLE
Can't heal other player with healing aura Ver. 1.15.2-3.6.14

### ISSUE THREAD

**Issue by bezant07** [RobertSkalko/Mine-and-Slash#222]
So im playing on my minecraft server and healing aura doesnt seems to  work, spell heals other mobs and me but it cant heal my friend. Im new to this mod and maybe i just dont understend somthing, im on level 2 and my freind on level 3. I dont see any errors on server and i dont see conflicts with other mods (they are not global, just backpacks, wall jump etc.

**Comment by RobertSkalko** [comment]
Join a party so you can heal your friend. Vanilla teams should work. Ill check if the spell heals mobs, it shouldnt

**Comment by RobertSkalko** [comment]
I can't reproduce mobs being healed.

**Comment by bezant07** [comment]
> Join a party so you can heal your friend. Vanilla teams should work. Ill check if the spell heals mobs, it shouldnt
Thanks for the quick reply! And thanks for this great mod. Also by mobs i meant tamed wolfs and cats, that was a bit unclear statment from my side.

**Comment by bezant07** [comment]
Just tried healing with vanilla teams,  unfortunately its not working.

**Comment by RobertSkalko** [comment]
That means it works perfectly. I made it so tamed pets are considered allies.

**Comment by RobertSkalko** [comment]
I just checked, yeah it only works on /slash teams if they are functional. Next update should fix it but won't be soon as i'm working on something else.

**Comment by bezant07** [comment]
> I just checked, yeah it only works on /slash teams if they are functional. Next update should fix it but won't be soon as i'm working on something else.

Yes thats works, thank you and good luck!
