### ISSUE TITLE
Cant open hub

### ISSUE THREAD

**Issue by leprechaunne** [RobertSkalko/Mine-and-Slash#223]
Using the mod in a custom pack (and also with only the mod to test), H cannot open the hub, so my server cant use the vast majority of the mod.

Using: the twitch loader, minecraft 1.12.2,  forge-14.23.5.2854, Java 8, and tested several versions of the mod, none of them were able to open the hub. There are also no options to change the bind, even in the config files as far as i can tell. Is there any work around?

**Comment by RobertSkalko** [comment]
1.12 doesnt have the hub, only 1.15
