### ISSUE TITLE
[1.12.2] [Multiplayer] Multiple Map Devices Overwrites with most Current Map Created

### ISSUE THREAD

**Issue by defranke00** [RobertSkalko/Mine-and-Slash#224]
On the World of Dragons Official server, I created a map device and inserted a mythical map. Got some good gear, and I was looking forward to going on another adventure today. Lo-and-behold, when I entered my portal today, I was now in a map 20 levels below the map I was playing, and a completely different biome. When exiting with the Leave Pearl, I was ejected to another player's base. The player was online, and after talking with him, I discovered he had just recently constructed his own Map device and activated it. Now whenever I enter my portals, it takes me to his maps. Thinking this curious, I inserted a new map into my device, and had him jump into his own portals, then leave with his pearl, then like clockwork, he appeared right next to my map device.

Problems: 
Creating a new map overwrites all existing maps, making them all the same.
Unable to have multiple different maps running at same time. 
Unable to have multiple parties on same server playing different maps. 
Appearing at a different Map device than the entered portal.

**Comment by AzureDoom** [comment]
This actually a vanilla bug sadly.

**Comment by RobertSkalko** [comment]
Azure i'm pretty sure that's false. I must have accidentally fixed it in my 1.14 port i think. Please update to 1.15 as 1.12 is no longer supported.

**Comment by defranke00** [comment]
Will gladly update to 1.15 when the modpack creater updates to 1.15.2 (which probably won't happen)
