### ISSUE TITLE
Main Hub key missing

### ISSUE THREAD

**Issue by matarata2001** [RobertSkalko/Mine-and-Slash#226]
Im playin a mod pack and i dont have any key to open the Main Hub to see the info

**Comment by RobertSkalko** [comment]
only 1.15 versions have the main hub. If youre on 1.15, change the keybinding

**Comment by matarata2001** [comment]
> only 1.15 versions have the main hub. If youre on 1.15, change the keybinding

ahh thank you im playing o 1.14.4 thats why then
