### ISSUE TITLE
Playing LAN; how to consider another player an ally?

### ISSUE THREAD

**Issue by MythyMajestic** [RobertSkalko/Mine-and-Slash#229]
Right, so I was playing this LAN on a singleplayer world with a friend of mine. However, I noticed that we were pretty easily able to damage each other, just as you'd expect, and that area buff spells, such as the Divine mage's AoE healing, only affected myself and not her. 

Is there a system in place, or a recommended mod, to allow for partying and marking someone as friendly?

**Comment by RobertSkalko** [comment]
vanilla teams or /slash teams
