### ISSUE TITLE
[1.15.2] Re-rolling a Prefix/Suffix Get One of the Two Results Most of the Time

### ISSUE THREAD

**Issue by stop-x13** [RobertSkalko/Mine-and-Slash#230]
I tried to re-roll prefix/suffix of a weapon, but it seems always having one of the two result. The weapon is at lv50+.
For prefix: it’s mostly either “hard hitting” or “life stealing”, I never get those negative prefixes “broken”, “colossal” and positive prefixes “heavenly strikes”, super rarely “magic siphon”.
For suffix: it’s mostly either “critical hits” or “critical damage”, I never get “the cactus” for swords, “vampirism”, “critical unity”, “force”, and I got “rock piecing”, “magic stealing” once.
I’m not sure if these prefixes/suffixes have a different weighting (most likely YES) and I understand some of the prefixes/suffixes are just butter than their worse counterpart, for example, “critical unity” is a better counterpart of “critical hits” and “critical damage” so this should have a lower weight, but it seems that this is almost impossible to get, not only “critical unity” but all other prefixes/suffixes mentioned above are just too rare, given that each re-roll add 25 instability and quickly the gear will have high chance of breaking.
I think this should be re-considered or having a config to be able to change these weights.

**Comment by RobertSkalko** [comment]
Affixes are datapacks, meaning you can configure them 100% to your liking.
