### ISSUE TITLE
[1.12.2] Missing healthbar after removing.

### ISSUE THREAD

**Issue by rater193** [RobertSkalko/Mine-and-Slash#237]
I was talking to the developer over discord, and i think there was a bit of misscommunication. I really like the mod, and i would love to use it, but it didnt go well with my pack so i had to remove it. When i removed it, it completely bugged the healthbars, and removed the healthbars.

When i brought this up to the developer he freaked out and banned me off his discord, and blocked me.
https://i.imgur.com/DxrUu5E.png

If you are reading this McRobertx22, i really like the mod, idk why you banned me, can you also unban me too? all i was trying to do was get help with an issue the mod caused.

screenshot of what it did ingame
https://i.imgur.com/meC1fak.png

I dont want to delete the world to fix this issue, people have put in to much time and effort into it.

**Comment by rater193** [comment]
all i want is guidance on how to fix it without deleting the world.

**Comment by RobertSkalko** [comment]
1.12 isn't supported, and spamming me will get you no help.

**Comment by rater193** [comment]
can you unban me off the discord? you overreacted, all i was trying to do was get help. I really like the mod, and idk why i was banned off the discord.

**Comment by rater193** [comment]
> 1.12 isn't supported, and spamming me will get you no help.

sorry if i bothered you, i was just trying to get help. can you please unban me off the discord? idk why you banned me.
