### ISSUE TITLE
Tetra (Mod) modified swords stop working with Mine and Slash installed (1.15.2)

### ISSUE THREAD

**Issue by CCleanerShot** [RobertSkalko/Mine-and-Slash#253]
I currently only have the 2 mods installed (and their dependencies). The auto-compatibility is enabled in serverconfig. 

https://www.youtube.com/watch?v=BR4S9PCfl40 
here is a video demonstration of the problem at hand.

like the title says, swords that originally have the mine and slash modifications and damage, no longer work as swords after being modified thru the Tetra mod, I went thru the entire process in survival (if you needed a demonstration for that too let me know) as well. Both when modifying the entire sword-type (example, for stone to iron) or just applying a single modifying. 

Seems that Tetra creates an entirely new sword, and the Mine and Slash never bothers applying new suffixes, or reminding to keep the old suffixes. This seems to be Tetra problem, but your prior mod (Mine and Slash Auto Compatibility) listed this as a mod compatibility, so I've posted it here.

_The Mine and Slash Auto Compatibility mod also doesn't have compatibility with Tetra on 1.15.2, (I haven't tested it on the suggested and supported 1.14.2). I assume that this particular thing isn't worth fixing, but just something worth pointing out._

**Comment by RobertSkalko** [comment]
Please check authors, that compatibility mod wasn't made by me. The name is also not perfect, all it means is items from that mod can get stats, not that there was any specific work done to ensure there's no incompatibilities.

Tetra also seems impossible to be made compatible. Use one mod or the other.
