### ISSUE TITLE
[SUGGESTION] Config option to have NPC levels scale to your level

### ISSUE THREAD

**Issue by imadethisaccountjusttosuggestthis** [RobertSkalko/Mine-and-Slash#256]
I have a base with lots of precious items and buildings, and therefore am faced with a dilemma: Be stuck with mobs under my level or say goodbye to my base to travel outward?
I'd say this is a pretty simple suggestion concept-wise. In singleplayer, all mobs should be your level (maybe with some random per-mob variation of -X or +X levels or a custom offset like "all mobs are 1 level higher than the player").
In multiplayer, you could either disable this option or make it so mobs are the average/highest/median of all nearby players.
Thanks for reading.

**Comment by RobertSkalko** [comment]
That option already exists: dimension configs > scale mobs to player level
