### ISSUE TITLE
Server Missing Shield Textures

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#27]
Server Every shield is missing their texture，Is it my problem?

**Comment by RobertSkalko** [comment]
contact the mod author, he probably did what i did before, which was replacing the renderer instance instead of just giving the shield a special rendererer. Tell him this if you want him to fix it.

**Comment by RobertSkalko** [comment]
This was actually a problem on my end. Was fixed in last update.
