### ISSUE TITLE
Mods incompatibility with other mods who adds weapon and stuff

### ISSUE THREAD

**Issue by IvorAmlug** [RobertSkalko/Mine-and-Slash#272]
This is more a question than a issue since it might be intended

I run my self into a little problem while i like the idea behind the mod i realised it makes weapons from other mods for example Ice and Fire obsulete they deal no damage anymore. While the creatures seem to work perfectly fine and some of them even spawn with an veteran rank etc. The weapons seem to become useless. Is there any way arround this? Or is my only option to remove this mod?

**Comment by RobertSkalko** [comment]
https://github.com/RobertSkalko/Mine-and-Slash/wiki/Compatible-Items

**Comment by IvorAmlug** [comment]
ahh okay thx
