### ISSUE TITLE
[1.15.2] Possible Performance Issues

### ISSUE THREAD

**Issue by cobbkris** [RobertSkalko/Mine-and-Slash#273]
I created a modpack for 3 people to enjoy, and I have been experiencing performance issues that I believe stem from this mod.  You can see the list of mods here (v0.1):  https://gitlab.com/cobbkris/magitech-modpack.  I am unable to even join my local server or a local LAN play.  I get an error that I have attached as a picture.
I have removed a ton of mods and kept yours in, and as you can see (I attached a txt file with the list of mods in "v0.2") most of these mods should not have any issues at all.  I was able to join the server and play for a while, then I get stuttering with no FPS issues (steady 60 FPS).  This happens both on the server and eventually in single player.  
System Specs:  
Ryzen 5 2600
16 GB RAM
nVidia GTX 1080

Is there any performance related changes I can make to the config file?
I can do more testing if you would like.
[modlist2.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/5398413/modlist2.txt)
![mc error1](https://user-images.githubusercontent.com/34900042/96389430-97c84200-117d-11eb-8148-8139389a396e.png)

**Comment by RobertSkalko** [comment]
Send a full log from server. Something is trying to send a packet above maximum size.

**Comment by cobbkris** [comment]
[2020-10-18-1.log.gz](https://github.com/RobertSkalko/Mine-and-Slash/files/5404337/2020-10-18-1.log.gz)
Attached is the log from yesterday when I tried to connect and it immediately disconnected.  Thanks for looking at this.

**Comment by RobertSkalko** [comment]
Too many errors. And none from my mod. I don't think my mod is the issue here. 
You are welcome to test without mine and slash but i'm closing as i don't plan to do any big updates for 1.15. And it's above the scope of the current 1.15 maintainer.
