### ISSUE TITLE
1.16.4 Forge Support?

### ISSUE THREAD

**Issue by KatoNamus** [RobertSkalko/Mine-and-Slash#278]
Hi RobertSkalko

First off; thank you so much for this mod. I've had many hours of fun with it in my personal Vivecraft 1.15 pack. Vivecraft dev(s) has unfortunately decided to drop 1.15 support and is now working on 1.16.4 only and only Forge mods work with Vivecraft, not Fabric.
Is there a way that the current Mine and Slash can work in 1.16.4 so that you don't have to make major changes to it and/or can just "bundle-compile" it along with the 1.15 version you're supporting?
If not, will you be supporting 1.16.4 at any point? Please?

**Comment by RobertSkalko** [comment]
No that isn't possible. Can't promise anything about the port right now.

**Comment by KatoNamus** [comment]
Bummer. Okay, thank you.
