### ISSUE TITLE
Support for 1.16?

### ISSUE THREAD

**Issue by AlexTheDolphin0** [RobertSkalko/Mine-and-Slash#286]
The title says it all

**Comment by TheLewtz** [comment]
wondering also, as 1.16 looks to be the new 1.12 more than liekly with 1.17 adding new java stuff which looks to require forge rewrite, along with new rendering with opengl update.   Working on a big modpack with some friends, and would like to use this if it ever becomes 1.16 compatible.

**Comment by KatoNamus** [comment]
+1

**Comment by leyxcx** [comment]
> wondering also, as 1.16 looks to be the new 1.12 more than liekly with 1.17 adding new java stuff which looks to require forge rewrite, along with new rendering with opengl update. Working on a big modpack with some friends, and would like to use this if it ever becomes 1.16 compatible.

1.17 isn't going to require a rewrite fyi. A dev has said small parts may need redesigning and rewriting but it wouldn't affect the whole of forge as a java version upgrade won't be a big deal :D

**Comment by RobertSkalko** [comment]
The latest version is called Age of Exile and it's for fabric 1.16.

I can only maintain one version at a time due to time limitations and the sheer amount of work the mod is.

**Comment by RobertSkalko** [comment]
done

**Comment by AlexTheDolphin0** [comment]
Me: oo what's this notification?
Also me: wait what's this mod
me after checking the curseforge page: oh yeah this mod
me: immediately adds to my 1.16 mod collection
