### ISSUE TITLE
Add support for silent gems scaling health

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [RobertSkalko/Mine-and-Slash#29]
So this mod sounds great but my health mod of choice is easily SilentChaos scaling health. If you can make sure this mod does not conflict with that one I will test your mod in my project. To be honest your mod looks awesome.

**Comment by RobertSkalko** [comment]
What's the incompatibility? I don't alter vanilla health and i even made it so that my mod's hp is based off vanilla hp. I even added configs that can alter the conversion rate.

**Comment by P3rf3ctXZer0** [comment]
Oh your saying it should work then? If so I will give it a whirl. As long as your mod does not limit vanilla health or mess with health api it should be fine because @SilentChaos52 added his own health / max health machanics even to some enemies code named blights.

**Comment by RobertSkalko** [comment]
My mod doesn't change vanilla hp at all. What it does is change entity vs entity damage to suit my mod's health. (which includes vanilla hearts converted to my hp)

In 1.14 update ill allow config option to show vanilla hp to reduce some confusion.

**Comment by RobertSkalko** [comment]
closing. in case its an issue, reopen.
