### ISSUE TITLE
1.17please!!!

### ISSUE THREAD

**Issue by blood789** [RobertSkalko/Mine-and-Slash#293]
1.17 has been released, I really hope to be able to play this mod in the latest version！

**Comment by AzureDoom** [comment]
You know this mod isn't even on 1.16.5 right? You want 1.16+, use Age of Exile, the Fabric remaster

**Comment by RobertSkalko** [comment]
Sorry, but 1.17 is 100% getting skipped. Who knows maybe even 1.18 will be skipped. But it's likely i'll go from 1.16 to 1.18 or 1.19.
