### ISSUE TITLE
The new 1.16.5 version isn't working at all

### ISSUE THREAD

**Issue by toffi3** [RobertSkalko/Mine-and-Slash#299]
As in the title, there is no crashlog or anything
![xd1](https://user-images.githubusercontent.com/84127414/138768154-d74d713a-5ae4-4ed2-9ec0-aa70c88782c7.png)
![xd2](https://user-images.githubusercontent.com/84127414/138768160-3373fa85-c6a8-4222-b4dd-1b888375b4e7.png)

**Comment by RobertSkalko** [comment]
This should be fixed with newest version, should tell what's missing now.
