### ISSUE TITLE
[1.16.5]Age Of Exile(mmorpg) has failed to load correctly

### ISSUE THREAD

**Issue by LinJonKur** [RobertSkalko/Mine-and-Slash#304]
I installed Mine_and_Slash_BETA-1.16.5-3.0.1(1.16.5) and the required dependencies and I got this error when trying to start minecraft. It says "java.lang.NoSuchMethodError". Mine and Slash and the dependencies are the only mod installed so what could it be?

**Comment by RobertSkalko** [comment]
I forgot to add dependencies to forge config, so they are currently only shown on the curseforge page for the file. Wll be fixed next update

**Comment by RobertSkalko** [comment]
This should be fixed with newest version, should tell what's missing now.
