### ISSUE TITLE
Mutant beasts compatibility.

### ISSUE THREAD

**Issue by nomadSky** [RobertSkalko/Mine-and-Slash#305]
Hello there!
How can i config this mod for supporting some of creatures that MB add? 
I mean, is there any config file with list of affected mobs? I want to change it.

**Comment by RobertSkalko** [comment]
What exactly do you need?

All mobs are auto affected. But there are datapacks that allow some customization of them called entity configs

**Comment by nomadSky** [comment]
Okay, I'll look for it.

**Comment by RobertSkalko** [comment]
I'd still like to know what exactly you need. That way I can know if the datapack will actually help you.
