### ISSUE TITLE
Better system for defying mod levels

### ISSUE THREAD

**Issue by sirben99** [RobertSkalko/Mine-and-Slash#307]
Hey!

I personally dislike the "go further from spawn to get higher level enemies" system and was wondering if there are any plans to change this? 
The issue with the current system is that it can feel really forced and unbalanced in a way. For example you found a very nice home spot thousands of blocks away, but every mob there one shots you. On the other hand if you stay in spawn you can just stay there and nothing will be a challange because the mobs are wayyyy below ur current level. And if you want a challenge youd have to go hunderds of thousands of blocks away to get one (Abit over exassuraded but i hope you get what i mean). Bottom point being ur freedom is limited by this system and its very unbalanced based on what point of the game ur in.

Maybe a system where mobs would be given levels based on ur level on given radius ur in, and if you have more than one person nearby the mob level would be counted accortingly to both players level. Maybe calculate what skills, lvl, items, item rarity etc and then base off the mob lvl on that, like a progressive difficulty system that defines how hard the mobs will be. 

These are just suggsections i had in mind, i dont know how doable this all is but id like to hear ur opinion!

**Comment by nomadSky** [comment]
>Maybe a system where mobs would be given levels based on ur level

It's configurable in mod options.

**Comment by RobertSkalko** [comment]
> On the other hand if you stay in spawn you can just stay there and nothing will be a challange because the mobs are wayyyy below ur current level.

I'm coincidentally doing something to try fix this. An experimental new feature coming up is basically a port of scaling health but made for mine and slash levels in mind.

In short as more time passes and you kill mobs, the difficulty per player goes up. Mobs get extra levels, and if there aren't any more extra levels to give, they become stronger instead.

This will be EXPERIMENTAL which means I have no idea if i'll keep it, discard it, or tweak it.

**Comment by sirben99** [comment]
Awesome! I had scaling health in mind while writing this, so im glad ur experimenting with that type of system. And even if you deside to discard it i appriciate the effort! 

Thank you both for informing me about the config option! The game crashes on startup for 1.16 (Ive read that ur already aware of this), but ill try the option in 1.15 in the meanwhile.

Thank you for taking ur time to answer! You can close this if you want to since the issue has been asnwered, i wont close it just incase you want to keep it open.

**Comment by RobertSkalko** [comment]
Sure, if you want to keep playing 1.16, just downgrade the dungeons of exile version 1 version.
