### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by stradar21** [RobertSkalko/Mine-and-Slash#309]
1.16.5
Forge 38.2.8
Mine_and_Slash_BETA-1.16.5-3.0.2.jar
[crash-2021-11-02_19.49.33-client.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/7464621/crash-2021-11-02_19.49.33-client.txt)

We have this on our server.

**Comment by RobertSkalko** [comment]
Should be fixed? Forgot about this one
