### ISSUE TITLE
[Suggestion] Add config option for spell damage multiplier or buff damage spells

### ISSUE THREAD

**Issue by Fogrits** [RobertSkalko/Mine-and-Slash#31]
The title explains itself.

Magic Spells does VERY LITTLE damage compared to regular weapons (swords and bows)

I found a level 6 fireball that does less damage than my lv1 common starter sword, why bother using magic then?

**Comment by RobertSkalko** [comment]
Did you try Collecting a matching jewerly set that amplifies spell dmg?

I added a "spell damage" stat that while it gives a bit less dmg, it applies to every spell. Meaning it should be much easier to gear up for spell damage now. I'll see about the config

**Comment by RobertSkalko** [comment]
are spells still weak btw? i buffed them a lot

**Comment by Fogrits** [comment]
Haven't tested them yet, gonna test it later today

**Comment by VeloxAzo** [comment]
Early game, magic still feels incredibly weak. Other people on the server are saying it's not worth touching until level 20+ with mythical spells. Playing "The Adventures of Halk" pack on the main server. 2.1.0

The nova spells also are really inconsistent. Feels impossible to hit things I'm not within one block of, and at the same height as.

**Comment by RobertSkalko** [comment]
as spells were buffed and nova was fixed, closing this.
