### ISSUE TITLE
Game crash when dying.

### ISSUE THREAD

**Issue by nomadSky** [RobertSkalko/Mine-and-Slash#310]
[crash-2021-11-04_03.53.15-client.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/7471332/crash-2021-11-04_03.53.15-client.txt)

Problem in title. When I die, minecraft just crash.
I suppose that this is related to the new difficulty mechanic in this mod and penalty after death.

Also, Is it compatible with scaling health and improved mobs? I already use these mods, which affect mobs HP.

**Comment by RobertSkalko** [comment]
You don't need scaling healh, I ported it in mine and slash and called it scaling difficulty. It should be more balanced because it accounts for mns levels.

**Comment by RobertSkalko** [comment]
Bug will be fixed next patch.

**Comment by nomadSky** [comment]
Okay. But what about blight mobs? I installed scalling health only for it and this is such a great innovation, don't want to disable it.

I can try to disable difficulty scaling in scaling health via set maxdif parameter to 0,  but I'm afraid it will overwrite mine and slash one. 
In this case, I will need to disable this feature in your mod instead.

**Comment by RobertSkalko** [comment]
> but I'm afraid it will overwrite mine and slash one

It won't.

>In this case, I will need to disable this feature in your mod instead. How can I do it?

Configs. But you don't need to.

**Comment by nomadSky** [comment]
>It won't.
Okay, I'll try it and give feedback.
