### ISSUE TITLE
[Feedback] [1.16.5] Letting us scrap the souls off of gear without destroying the gear

### ISSUE THREAD

**Issue by ProvoGo** [RobertSkalko/Mine-and-Slash#312]
MnS BETA 1.16.5 version 4.0.6

With the ways souls works now you end up going through an insane amount of resources trying to put them on things because you have to keep on making new gear.

It would be great to have a way to strip souls off of gear, kind of like how the grindstone works with enchants, just straight up void them so you can use the gear again.

(not sure if this the the correct issue tracker for this but i dont know where else to post it)

**Comment by RobertSkalko** [comment]
I'm thinking of instead making the souls identifiable. I don't like the idea of scraping souls off gear unless it's a costly currency item.

**Comment by ProvoGo** [comment]
making the souls identifiable would also solve it, wouldnt have to waste a piece of gear if that was the case.

**Comment by nomadSky** [comment]
> I'm thinking of instead making the souls identifiable. I don't like the idea of scraping souls off gear unless it's a costly currency item.

Agreed.

**Comment by RobertSkalko** [comment]
Implemented identification.
