### ISSUE TITLE
[suggestion] reskillable like stats requirements 

### ISSUE THREAD

**Issue by nomadSky** [RobertSkalko/Mine-and-Slash#313]
Hello there! Like your mod.
Are there any plans to implicate the reskillable-like system, where is specific actions requires stat upgrade? For example, for using diamond sword you need to lvlup attack paramater to 24. It works the same with placing blocks, mining and harvesting. 
I think it would be great addition to complex system of your mod.

**Comment by RobertSkalko** [comment]
Can you explain a bit further?

I already have my own level system which is used for wearing higher level gear.

What else would you want besides a copy of reskillable? How would my version differ enough to justify cloning that mod? I did do that for some things, like my scaling difficulty to account for my level system, but I don't see a reason for this one.

**Comment by nomadSky** [comment]
Uh, yes. I'm not native english speaker, so sorry if I can speak tongue-tied.

I'm talking about this: you could levelup strength in your mod to X points, for example. And you will be able to gain access to the armor, protection points of which do not exceed Y number. This can work procedurally, like in IguanaTweaks where weight of armor (and concomitant movement speed debuff couse of this) based on the defence, so it's compatible with almost all mods. 

I hope you understood me. Just wanted do hear your opinion on this.

**Comment by RobertSkalko** [comment]
I don't think ill do anything like this soon but If anyone wants I think making a small addon that caps reskillable levels to mine and slash levels isn't that hard.
