### ISSUE TITLE
Hello. 1.16.5 custom add compatible with how to add multiple format tried many are wrong

### ISSUE THREAD

**Issue by ricemoon** [RobertSkalko/Mine-and-Slash#317]

**Comment by RobertSkalko** [comment]
Show what you tried

**Comment by ricemoon** [comment]
gear_compatibility = ["aoa3:gods_greatblade:sword"]["aoa3:knights_guaed:sword"]

	gear_compatibility = ["aoa3:gods_greatblade:sword"]
["aoa3:knights_guaed:sword"]


	gear_compatibility = ["aoa3:gods_greatblade:sword"]
	gear_compatibility = ["aoa3:knights_guaed:sword"]



The above are not
Only one change in the default format

**Comment by RobertSkalko** [comment]
gear_compatibility = ["aoa3:gods_greatblade:sword","aoa3:knights_guaed:sword"]

Blame forge for not having ingame config editing.
