### ISSUE TITLE
@obertSkalko 1.16.5 to customize a format compatible with multiple equipment example? Thank you

### ISSUE THREAD

**Issue by ricemoon** [RobertSkalko/Mine-and-Slash#319]

**Comment by RobertSkalko** [comment]
The config file? It has its own example: "minecraft:diamond:sword"
Item id, then the mine and slash gear slot datapack id, in this case it's "sword"

**Comment by ricemoon** [comment]
Add multiple consecutive
[" minecraft: diamond: sword "/ minecraft: diamond: sword"]
Like this?

**Comment by ricemoon** [comment]
> Add multiple consecutive
> [" minecraft: diamond: sword "/ ”minecraft: diamond: sword"]
> Like this?

**Comment by RobertSkalko** [comment]
["minecraft: diamond: sword ", ”minecraft: diamond: sword"]
Like this
