### ISSUE TITLE
Several Questions of 1.16.5

### ISSUE THREAD

**Issue by dovakhiins** [RobertSkalko/Mine-and-Slash#322]
1. I think there may be something wrong with the energy system. The cost per slash is as much as 20(maybe the same as the physical damage?), making the 1vmulti battle extremely difficult.
2. What is the new way to get to the dungeon dimension? It must be different from former versions.
3. I think the idea of attaching souls to equipments is brilliant, but it will be much better to support more types of weapons(like the guns in AoA3).
4. Are gems and runes really on the loot list? I havnt find any so far.

**Comment by RobertSkalko** [comment]
As with most new content, energy will need to be balanced. The dungeon dimension is currently wip (well i'm making a replacement). Guns are kind of last on my priority list as I personally dislike them AND they always seem to have compat issues with damage code. The gems i'm not sure, i'll check after my next playthrough after i'm less busy.

Glad you like the new soul system, I wasn't entirely confident of it!

**Comment by dovakhiins** [comment]
Thank you for your reply! Looking forward to the release version!
