### ISSUE TITLE
Potion effect name needs localizing.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#33]
![2019-06-30_13 45 38](https://user-images.githubusercontent.com/4427684/60402357-abe0ce00-9b4b-11e9-998d-319ff33ac147.png)

effect.mmorpg.self_regen

This was obtained by eating a Tombstone candy that you get on Halloween, or if you are a donor, it gives any random effect even the bad ones.

**Comment by RobertSkalko** [comment]
fixed in next build. minor issue i forgot
