### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by MrTailson** [RobertSkalko/Mine-and-Slash#330]
Please update your dependencies on the mod page. The only one listed there is Curios, when my crash report told me I needed 3 other things at start up. The Library of Exile, Divine Missions, and something else called World of Exile, which I can't even find out there
[crash-2022-02-27_13.10.47-fml.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/8149291/crash-2022-02-27_13.10.47-fml.txt)
.

**Comment by RobertSkalko** [comment]
They are listed on each file.

**Comment by MrTailson** [comment]
> 

What does this mean? I can't find the dependencies to download. I'm missing just one left and it is not listed.

**Comment by MrTailson** [comment]
I found the dependencies under the file version for 1.16. I didn't know there could be different dependencies based on the version, and that they would be listed underneath the patch notes. I'm sorry for the inconvenience. I'm still new at this.
