### ISSUE TITLE
[1.14.3] Crashes on loading dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#34]
Crash - 
https://gist.github.com/ProsperCraft/83760f4c814e7ef4aeafe9e16034a1b0

 forge-1.14.3-27.0.16
Mods- Only 
Mine and Slash-1.14.3-2.0.3
curios-FORGE-1.14.3-0.13

Logs-
https://gist.github.com/ProsperCraft/ed8cf0db692b5b760f624bf2a4edf454
debug-
https://gist.github.com/ProsperCraft/3c3de2a030e05fae778e967b2de550f3

**Comment by RobertSkalko** [comment]
posted a fix on curseforge, sorry for the incovenience!

**Comment by ProsperCraft** [comment]
Fixed! Thank you!
