### ISSUE TITLE
Energy not being consumed

### ISSUE THREAD

**Issue by jackivy3** [RobertSkalko/Mine-and-Slash#359]
playing the craft to exile 2 modpack and no matter what i do im not using up any energy, able to attack dodge and do everything limitlessly. i reallly like the mod pack but kind of feel like im defeating the point of it and getting off easy when i really want a challenge. any idea how to fix this so im not basically abusing the game?

**Comment by RobertSkalko** [comment]
please don't send me modpack related issues. Cte2 made attacks cost 0 energy and that's what their dev wants
