### ISSUE TITLE
Stacktrace in console

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#36]
The server did that unexplained CME crash and rebooted while we were in the map dim, when we logged back in we were all dead with graves at 0 0 in the overworld.

This stacktrace was in console when I tried to log in...

https://gist.github.com/ProsperCraft/f7ae21f9d5b4016bc6b6d8426ff28dea

**Comment by RobertSkalko** [comment]
ill add some more safety to the saving. idk how but the crash seems to be because the player capability was null, which shouldnt ever happen that i know. The fact that graves were in 0 0 means all the checks failed in teleporting back to the original dimension, probably because of the crash.
