### ISSUE TITLE
[Feature Request] Side by side equipment compare like Diablo

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#37]
![B9WOB5SAQ8DU1463101447204](https://user-images.githubusercontent.com/4427684/60743260-0c964f00-9f2e-11e9-9b40-3fd0de01e5ca.jpg)

Would be very useful if we could press a key and mouse over equipment to bring up your current gear vs the gear you are moused over.

**Comment by RobertSkalko** [comment]
this is cool of course, but i dont see how to do that. When things are stable i might look into how to do this. shouldn't be too difficult, i assume just copy how game currently displays tooltips on the item currently equipped.. But depending on how close/obsfucated those methods are, could be really easy or really difficult.

**Comment by RobertSkalko** [comment]
closing cus this should be an addon/separate mod.
