### ISSUE TITLE
Copy jewelry BUG

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#4]
First of all, this module is very good, I like it very much, my friends like it too, I hope to continue to update.

In the server, click any jewelry from the jewelry bar and put it directly into the auxiliary handrail (shield bar). When the player transmits to other worlds, you can copy the jewelry.

Transfer refers to the use of a plug-in written with a transfer command (menu). After the transfer, the jewelry in the accessory bar (the shield bar) will appear again in the jewelry bar, so that the jewelry can be copied.

I know this is a bug in the Baubles mod, but I want you to know.

I am sorry that my English is not good. I am using Google Translate.
-------------------------------------------------------------------------------------------------
首先这个模组非常棒，我很喜欢，我的朋友们也很喜欢，我希望能够继续更新下去。

在服务器中，将任意饰品从饰品栏中点击直接放入副手栏(盾牌栏)，当玩家传送到其他世界后可以复制饰品。

传送是指使用写有传送命令(菜单)的插件进行传送 ，传送后当初饰品栏放入副手栏(盾牌栏)中的饰品会在饰品栏中再次出现一个，这样就可以复制饰品了。

我知道这是Baubles mod的BUG，但是我想让你知道。

很抱歉我的英语不好，我使用的是谷歌翻译。

**Comment by RobertSkalko** [comment]
Thanks, i also found 1 more baubles bug but i fixed it by removing the right click functionality. Let's see if i can make it so baubles can't be equipped in shield slots or something..

**Comment by RobertSkalko** [comment]
I'm porting the mod to 1.13 and i think i'll use another similar mod like baubles, curios. But even if i stay with baubles i'm sure the dupe bugs will be fixed in an update.
