### ISSUE TITLE
[Feature Request] Ability to link items in chat to show off.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#40]
Like this- https://forums.factorio.com/viewtopic.php?f=6&t=21974

So you can share your loots with other players, they can see their stats without having to list them.

**Comment by RobertSkalko** [comment]
This seems like one of those things other mods probably already do?

Any mods in 1.12.2 that do this?

**Comment by ProsperCraft** [comment]
Bukkit pluign - https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/

Apparently, Quark can do it as well-https://www.curseforge.com/minecraft/mc-mods/quark

**Comment by RobertSkalko** [comment]
Better press quark to update then. I don't like making duplcate features.

**Comment by RobertSkalko** [comment]
closing, in case quark doesnt want to come to 1.14.3 for a long time and no other mods get this feature, you can suggest again. I feel my mod is already bloated with features to add a general one too.

**Comment by ProsperCraft** [comment]
What if I don't want to add Quark to the pack?

Quark changes quite a bit of gameplay, some people don't like it.

**Comment by RobertSkalko** [comment]
i'm pretty sure quark can be configured almost completely, disabling and enabling parts.
