### ISSUE TITLE
[1.14.3] Server crash - Group map- NoSuchMethodError: com.robertx22.blocks.map_device.TileMapDevice.getRenderBoundingBox(

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#44]
Crash report-
https://paste.fedoraproject.org/paste/fa9U1Tm3vktiCP2gqSyL5A

Console- 
https://gist.github.com/ProsperCraft/403a3a46fb6615b187a9f55ddd071097

We tiered this up to tier 20 then jumped in to this group map.

Clean Debug log-
[debug.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3384421/debug.log)

Clean Latest log-
[latest.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3384422/latest.log)

Mod version - Mine and Slash-1.14.3-2.0.27
Forge version - forge-1.14.3-27.0.50

**Comment by RobertSkalko** [comment]
fixed in latest update. I accidentally used a client method on server.
