### ISSUE TITLE
[Feature Request] Do mild pregen of the map worlds while the server is over 19 TPS.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#45]
If the server TPS is above 19 pregen the map worlds, this will cause less violent lag when they are generating when the player goes there.

**Comment by RobertSkalko** [comment]
shouldn't there be other mods that pregen dimensions?

I also don't know how to pregen. 

Also here's from chunk pregenerator's mod author

> At the [24.6.2019] I tested the waters on how far forge is in there. Technically it is portable at that point, but so many features that ChunkPregen requires are not fully implemented yet. It is to the point where there is a massive performance hog or stability loss to the point where it is not acceptable. TL:DR I am waiting until Forge comes out of Alpha/Beta phase.

If it can't be done by other pregen mods then i might look into implementing it. Until then you can disable reset dimensions on reload and delete the files yourself whenever you feel the maps were exhausted.

**Comment by ProsperCraft** [comment]
Chunk Pregenerator has to be told to pregen a chunk.

What I propose would be to start a very slow crawling pregen of the dims when the server started but if Chunk Pregenerator who is the master of pregen can't do it yet, then it most likely isn't possible yet.
