### ISSUE TITLE
Duplication issue (latest version)

### ISSUE THREAD

**Issue by xhatz** [RobertSkalko/Mine-and-Slash#46]
Hello! So basically, when you open the special inventory (g) and shift click on a stack-able item inside of your inventory (while special inventory is open), this item duplicates itself over and over until it reaches 64.

Also, much smaller issue, when pressing the drop key on a item (q or a on my keyboard), sometimes other items just randomly pop ouf of my inventory too.

Thank you!

**Comment by RobertSkalko** [comment]
omg you're right. but i think this is a curios issue. im gonna test it right now

**Comment by xhatz** [comment]
Thank you :P!

And wow I didn't even know about the vanilla thing haha, my bad then ^^

**Comment by RobertSkalko** [comment]
Closing, fixed in newest curios API update.
