### ISSUE TITLE
Map Device (2.1.0 - 1.14.3)

### ISSUE THREAD

**Issue by Sustobk** [RobertSkalko/Mine-and-Slash#48]
Ive been playing with some friends, and when we use a Map, I (server Host, Map host) get teleported to the right map but they are teleported to a lvl 1 Map. Also when they come back they spawn under a block or in the nether.
Thx, awesome mod really enjoying it !

**Comment by RobertSkalko** [comment]
I'd need a bit more info. Are you sure you didn't go into the map of right level, but walked further into a lower level area?

Also, they should spawn back where the map device is. Do they have the map device in the nether? There's only one piece of code that can possibly spawn you into the nether and ill remove that in next update.

**Comment by Sustobk** [comment]
Hi ! Yep Map lvl is right as I see the mobs in the correct lvl. I forgot to
mention somthing, when he opens a Dragon Egg only item lvl 1/3 drops, but
it works fine for me (items drop match dungeon lvl)
Nope the device is at the normal world. When I get teleported back I spawn
right next to it but they spawn under lava.
Thx for your reply

**Comment by RobertSkalko** [comment]
Did the player that get lvl 1/3 drops sacrifice a lvl 1-3 map? Not sure if it's possible to get a map that low lvl.

**Comment by Sustobk** [comment]
OHHHHHHHHHHHH, Ive just check and I see I have only 1 map that says Group
Map. That measn all other maps are intended to do them solo ? If thats how
it works then we are having this issue because we always entered we all
with the same Map. They got teleported to an lvl 1 instance, maybe because
of that.

**Comment by RobertSkalko** [comment]
closing cus outdated, if you have more problems, open a new issue.
