### ISSUE TITLE
[request] 1.14 Crossbows and tridants as weapon bases. 

### ISSUE THREAD

**Issue by VeloxAzo** [RobertSkalko/Mine-and-Slash#49]
Bonus points if they use fancy scaling. For example, Tridants could be inherently magic + melee hybrids.

**Comment by RobertSkalko** [comment]
any suggestions for tridents?

seems u throw them, they arent in ur hand anymore and become projectiles. But my dmg system works based on the dmg of the weapon in ur hand.. Meaning i'd have to hardcode tridents to save player dmg on shoot and use that info.. 

Crossbows are easy. But i lack info on their enchantments, so not sure how to balance them.

**Comment by VeloxAzo** [comment]
Having them pre-enchanted with loyalty wouldn't work by the looks of it. My first thought would be to instead put the weapon on a cooldown when it is thrown and it fires a projectile instead of the weapon itself. The projectile disappears when it comes back off cooldown. 

If you're referring to just what the enchants do, they're listed on the minecraft gamepedia wiki. 
https://minecraft.gamepedia.com/Piercing

**Comment by RobertSkalko** [comment]
crossbows added. using vanilla mc items tho cus mc stupidly hard coded both their interaction it seems and their renderering. Either that or i screwed up something but not likely.

Tridents are harder tho

**Comment by iMoobert** [comment]
You could keep them in your hand and lose a little durability every time you throw one out, or have them stackable, kind of like how the Diablo II javelins work.

**Comment by Lanphrost** [comment]
Sorry to intrude, but what if instead of replacing vanilla tridents you add in your own variety. A thrown weapon set that you can code with your own rules instead of having to bend MC's. Could even branch out beyond tridents, to include spears and such.

**Comment by RobertSkalko** [comment]
Yes, but if someone wanted to make tridents compatible items, they wouldn't do any dmg if you use vanilla ones then.

**Comment by RobertSkalko** [comment]
i used a simple workaround specifically for tridents now. Basically whenever you throw a trident, i record the item into player's data. Then i use that too when calculating stats for a few seconds after that (if no other weapon is in hotbar) meaning that at worst this workaround would make melee attacking after throwing the trident work as if you still had it in your hand. Will see if i can get anything better but for now should work.
