### ISSUE TITLE
Unsalvagable BUG

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#5]
Hello, I like this module very much. I have been playing with my friends for a week, which is great.

Feedback on a bug, the equipment obtained in the Newbie Gear Bag can be recycled in the Gear Salvage Station to get Ore.

My English is not very good, I am using Google Translate.
--------------------------------------------------------------------------------------------------------------
您好，我很喜欢这个模组，我和朋友们已经玩了一个星期，这很棒。

反馈一个BUG，Newbie Gear Bag中获得的装备可以在Gear Salvage Station中回收获得Ore。

我的英语不是很好，我使用的是谷歌翻译。

**Comment by RobertSkalko** [comment]
Thanks, this should be fixed in a hotfix!
