### ISSUE TITLE
Dimension ID invalid

### ISSUE THREAD

**Issue by HamzasHere** [RobertSkalko/Mine-and-Slash#50]
My server crashes when I try using a map on the map device. I've changed the dimension ID a few times to random numbers but it's always invalid. 
I'm using mine and slash 1.6.19 and forge 14.23.5.2838

[crash-2019-07-20_16.24.02-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/3413682/crash-2019-07-20_16.24.02-server.txt)

**Comment by HamzasHere** [comment]
I don't know if I'm supposed to copy the text file or not so I'll also paste it here.

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2019-07-20 16:24:02 AST
Description: Ticking block entity

java.lang.IllegalArgumentException: Invalid dimension id 1462
    at net.minecraft.world.DimensionType.getById(DimensionType.java:77)
    at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:131)
    at com.robertx22.saveclasses.MapItemData.createDimension(MapItemData.java:136)
    at com.robertx22.blocks.map_device.TileMap.doLogic(TileMap.java:108)
    at com.robertx22.blocks.map_device.TileMap.update(TileMap.java:70)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zzp000(World.java:5132)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: mmorpg:map_device_entity // com.robertx22.blocks.map_device.TileMap
  Block type: ID #392 (tile.mmorpg:map_device // com.robertx22.blocks.map_device.BlockMap // mmorpg:map_device)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-548,221,-19), Chunk: (at 12,13,13 in -35,-2; contains blocks -560,0,-32 to -545,255,-17), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
  Actual block type: ID #392 (tile.mmorpg:map_device // com.robertx22.blocks.map_device.BlockMap // mmorpg:map_device)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {x:-548,y:221,ForgeCaps:{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}},z:-19,Items:[],id:"mmorpg:map_device_entity"}

-- Affected level --
  Level name: PointFourForRealSpawn
  All players: 1 total; [GCEntityPlayerMP['Hamadawana'/102076, l='PointFourForRealSpawn', x=-548.74, y=219.00, z=-19.87]]
  Chunk stats: ServerChunkCache: 245 Drop: 0
  Level seed: 1738271132534238504
  Level generator: ID 31 - lostcities_bop, ver 0. Features enabled: true
  Level generator options: { "profile": "rarecities" }
  Level spawn location: World: (-224,64,248), Chunk: (at 0,4,8 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 1213515 game time, 1495874 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 35077 (now: false), thunder time: 15225 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_211, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2726908264 bytes (2600 MB) / 4118806528 bytes (3928 MB) up to 4118806528 bytes (3928 MB)
  JVM Flags: 2 total; -Xmx4G -Xms3G
  IntCache: cache: 0, tcache: 8, allocated: 11, tallocated: 96
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 152 mods loaded, 152 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version                  | Source                                            | Signature                                |
       |:------ |:--------------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                               | 9.42                     | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                             | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | micdoodlecore                     |                          | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfixcore                       | 7.7.4                    | minecraft.jar                                     | None                                     |
       | LCHIJA | obfuscate                         | 0.2.6                    | minecraft.jar                                     | None                                     |
       | LCHIJA | opencomputers|core                | 1.7.4.153                | minecraft.jar                                     | None                                     |
       | LCHIJA | srm-hooks                         | 1.12.2-1.0.0             | minecraft.jar                                     | None                                     |
       | LCHIJA | randompatches                     | 1.12.2-1.17.1.0          | randompatches-1.12.2-1.17.1.0.jar                 | None                                     |
       | LCHIJA | bspkrscore                        | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar            | None                                     |
       | LCHIJA | treecapitator                     | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar             | None                                     |
       | LCHIJA | adminshop                         | 1.0                      | adminshop-1.3.2.jar                               | None                                     |
       | LCHIJA | infinitylib                       | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                            | None                                     |
       | LCHIJA | agricraft                         | 2.12.0-1.12.0-a6         | AgriCraft-2.12.0-1.12.0-a6.jar                    | None                                     |
       | LCHIJA | aoa3                              | 3.1.2.b                  | AoA3-3.1.2.b.jar                                  | None                                     |
       | LCHIJA | placebo                           | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                          | None                                     |
       | LCHIJA | apotheosis                        | 1.10.2                   | Apotheosis-1.12.2-1.10.2.jar                      | None                                     |
       | LCHIJA | attributefix                      | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | jei                               | 4.14.4.260               | jei_1.12.2-4.14.4.260.jar                         | None                                     |
       | LCHIJA | quark                             | r1.5-168                 | Quark-r1.5-168.jar                                | None                                     |
       | LCHIJA | autoreglib                        | 1.3-31                   | AutoRegLib-1.3-31.jar                             | None                                     |
       | LCHIJA | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | avaritia                          | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar            | None                                     |
       | LCHIJA | baubles                           | 1.5.2                    | Baubles-Mod-1.12.2.jar                            | None                                     |
       | LCHIJA | biomesoplenty                     | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar     | None                                     |
       | LCHIJA | bonsaitrees                       | 1.1.3                    | bonsaitrees-1.1.3-b156.jar                        | None                                     |
       | LCHIJA | carryon                           | 1.12.2                   | CarryOn+MC1.12.2+v1.12.2.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHIJA | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
       | LCHIJA | chickens                          | 6.0.4                    | chickens-6.0.4.jar                                | None                                     |
       | LCHIJA | sanlib                            | 1.5.1                    | SanLib-1.12.2-1.5.1.jar                           | df48348748b5e141b1d118e2302a8d5be930b708 |
       | LCHIJA | claysoldiers                      | 3.0.0-beta.2             | ClaySoldiersMod-1.12.2-3.0.0-beta.2.jar           | None                                     |
       | LCHIJA | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                  | None                                     |
       | LCHIJA | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                          | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
       | LCHIJA | cofhworld                         | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cyclopscore                       | 1.4.0                    | CyclopsCore-1.12.2-1.4.0.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | colossalchests                    | 1.7.3                    | ColossalChests-1.12.2-1.7.3.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | combattagged                      | 1.12.2.009               | CombatTagged-1.12.2.009.jar                       | None                                     |
       | LCHIJA | morpheus                          | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
       | LCHIJA | comforts                          | 1.4.1.2                  | comforts-1.12.2-1.4.1.2.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | refinedstorage                    | 1.6.14                   | refinedstorage-1.6.14.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | compactmachines3                  | 3.0.18                   | compactmachines3-1.12.2-3.0.18-b278.jar           | None                                     |
       | LCHIJA | crafttweaker                      | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | cookingforblockheads              | 6.4.71                   | CookingForBlockheads_1.12.2-6.4.71.jar            | None                                     |
       | LCHIJA | corpse                            | 1.12.2-1.0.2             | corpse-1.12.2-1.0.2.jar                           | None                                     |
       | LCHIJA | cosmeticarmorreworked             | 1.12.2-v4a               | CosmeticArmorReworked-1.12.2-v4a.jar              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | culinaryconstruct                 | 1.3.3                    | culinaryconstruct-1.3.3.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | modcurrency                       | 1.12-1.3.11              | Currency-1.12.0-1.3.11.jar                        | None                                     |
       | LCHIJA | dimdoors                          | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                    | None                                     |
       | LCHIJA | dipomoneymod                      | 1.0.1                    | dipomoneymod-1.0.1.jar                            | None                                     |
       | LCHIJA | doggytalents                      | 1.15.0.5                 | DoggyTalents-1.12.2-1.15.0.5-universal.jar        | None                                     |
       | LCHIJA | patchouli                         | 1.0-20                   | Patchouli-1.0-20.jar                              | None                                     |
       | LCHIJA | mmorpg                            | 1.6.13                   | Mine+and+Slash-1.6.19.jar                         | None                                     |
       | LCHIJA | rcraft                            | 1.7.5                    | dotHack+Weapons-1.7.5.jar                         | None                                     |
       | LCHIJA | endercore                         | 1.12.2-0.5.59            | EnderCore-1.12.2-0.5.59.jar                       | None                                     |
       | LCHIJA | thermalfoundation                 | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion                  | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                           | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderiobase                       | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderioconduits                   | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | opencomputers                     | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar              | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | forestry                          | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                     | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | ftblib                            | 5.4.3.127                | FTBLib-5.4.3.127.jar                              | None                                     |
       | LCHIJA | enderiomachines                   | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderiopowertools                 | 5.0.46                   | EnderIO-1.12.2-5.0.46.jar                         | None                                     |
       | LCHIJA | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | everlastingabilities              | 1.5.1                    | EverlastingAbilities-1.12.2-1.5.1.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | flansmod                          | 5.5.2                    | Flan's Mod-1.12.2-5.5.2.jar                       | None                                     |
       | LCHIJA | wumpleutil                        | 2.12.6                   | wumpleutil-1.12.2-2.12.6.jar                      | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | LCHIJA | flourishingfoliage                | 1.0.2                    | flourishingfoliage-1.12.2-1.0.2.jar               | 1e57901a90acd4a3a54295b6decff5397be51a31 |
       | LCHIJA | foamfix                           | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                         | None                                     |
       | LCHIJA | forgeendertech                    | 1.12.2-4.4.21.1          | ForgeEndertech-1.12.2-4.4.21.1-build.0377.jar     | None                                     |
       | LCHIJA | forgelin                          | 1.8.3                    | Forgelin-1.8.3.jar                                | None                                     |
       | LCHIJA | ftbbackups                        | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.4.jar                   | None                                     |
       | LCHIJA | fxcontrol                         | 0.1.9                    | fxcontrol-1.12-0.1.9.jar                          | None                                     |
       | LCHIJA | galacticraftcore                  | 4.0.2.211                | GalacticraftCore-1.12.2-4.0.2.211.jar             | None                                     |
       | LCHIJA | galacticraftplanets               | 4.0.2.211                | Galacticraft-Planets-1.12.2-4.0.2.211.jar         | None                                     |
       | LCHIJA | grapplemod                        | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                       | None                                     |
       | LCHIJA | hammercore                        | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | hardcoredarkness                  | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | ichunutil                         | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | hats                              | 7.0.0                    | Hats-1.12.2-7.0.2.jar                             | None                                     |
       | LCHIJA | helpfixer                         | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                       | None                                     |
       | LCHIJA | icbmclassic                       | 1.12.2-3.3.0.63          | ICBM-classic-1.12.2-3.3.0b63.jar                  | None                                     |
       | LCHIJA | incontrol                         | 3.9.10                   | incontrol-1.12-3.9.10.jar                         | None                                     |
       | LCHIJA | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.12-236.jar        | None                                     |
       | LCHIJA | instantunify                      | 1.1.2                    | instantunify-1.12.2-1.1.2.jar                     | None                                     |
       | LCHIJA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest                         | 1.12.2-7.0.67.844        | Iron-Chests-Mod-1.12.2.jar                        | None                                     |
       | LCHIJA | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
       | LCHIJA | journeymap                        | 1.12.2-5.5.5b7           | JourneyMap-Mod-1.12.2-Unlimited.jar               | None                                     |
       | LCHIJA | locks                             | 2.2.1                    | Locks-2.2.1.jar                                   | None                                     |
       | LCHIJA | loottweaker                       | 0.0.10                   | LootTweaker-1.12.2-0.0.10.jar                     | None                                     |
       | LCHIJA | lostcities                        | 2.0.20                   | lostcities-1.12-2.0.20.jar                        | None                                     |
       | LCHIJA | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
       | LCHIJA | malisisdoors                      | 1.12.2-7.3.0             | MalisisDoors-Mod-1.12.2.jar                       | None                                     |
       | LCHIJA | mcjtylib_ng                       | 3.5.3                    | mcjtylib-1.12-3.5.3.jar                           | None                                     |
       | LCHIJA | radixcore                         | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar              | None                                     |
       | LCHIJA | mca                               | 1.12.2-5.3.1             | Minecraft-Comes-Alive-Mod-1.12.2.jar              | None                                     |
       | LCHIJA | mtrm                              | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar        | None                                     |
       | LCHIJA | testdummy                         | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                        | None                                     |
       | LCHIJA | monsterswarm                      | 2.0.1                    | MonsterSwarm-2.0.1.jar                            | None                                     |
       | LCHIJA | morph                             | 7.1.3                    | Morph-1.12.2-7.1.3.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | multimine                         | 1.6.0                    | MultiMine-1.12.2.jar                              | None                                     |
       | LCHIJA | multimob                          | 1.0.5                    | multimob-1.0.5.jar                                | None                                     |
       | LCHIJA | recipehandler                     | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar             | None                                     |
       | LCHIJA | neid                              | 1.5.4.4                  | NotEnoughIDs-1.5.4.4.jar                          | None                                     |
       | LCHIJA | nuclearcraft                      | 2.17b                    | NuclearCraft-2.17b-1.12.2.jar                     | None                                     |
       | LCHIJA | offlineskins                      | 1.12.2-v5g               | OfflineSkins-1.12.2-v5g.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | omlib                             | 3.1.0-232                | OMLib-1.12.2.jar                                  | None                                     |
       | LCHIJA | ompd                              | 3.1.0-61                 | ompd-1.12.2-3.1.0-61.jar                          | None                                     |
       | LCHIJA | openmodularturrets                | 3.1.0-335                | OpenModularTurrets-Mod-1.12.2.jar                 | None                                     |
       | LCHIJA | harvestcraft                      | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar                   | None                                     |
       | LCHIJA | placeableitems                    | 3.3                      | placeableitems-3.3.jar                            | None                                     |
       | LCHIJA | portality                         | 1.0-SNAPSHOT             | portality-1.12.2-1.2.3-15.jar                     | None                                     |
       | LCHIJA | primitivemobs                     | 1.2.3a                   | primitivemobs-1.2.3a.jar                          | None                                     |
       | LCHIJA | railcraft                         | 12.0.0                   | railcraft-12.0.0.jar                              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | randomloot                        | 1.3                      | RandomLoot-1.4.3.jar                              | None                                     |
       | LCHIJA | realdrops                         | 1.2.14                   | RealisticItemDrops-1.2.14.jar                     | None                                     |
       | LCHIJA | rftools                           | 7.71                     | rftools-1.12-7.71.jar                             | None                                     |
       | LCHIJA | rftoolscontrol                    | 2.0.2                    | rftoolsctrl-1.12-2.0.2.jar                        | None                                     |
       | LCHIJA | roost                             | 2.0.10                   | roost-1.12.2-2.0.10.jar                           | None                                     |
       | LCHIJA | ruins                             | 17.2                     | Ruins-1.12.2.jar                                  | None                                     |
       | LCHIJA | sanplayermodel                    | 1.1.1                    | SanLib-1.12.2-1.5.1.jar                           | None                                     |
       | LCHIJA | secretroomsmod                    | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                   | None                                     |
       | LCHIJA | sereneseasons                     | 1.2.16                   | SereneSeasons-1.12.2-1.2.16-universal.jar         | None                                     |
       | LCHIJA | shadowmc                          | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                           | None                                     |
       | LCHIJA | silentlib                         | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                   | None                                     |
       | LCHIJA | thermaldynamics                   | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | simplyjetpacks                    | 2.2.12.65                | SimplyJetpacks2-1.12.2-2.2.12.65.jar              | None                                     |
       | LCHIJA | specialai                         | 1.1.0_for_mc1.12.2       | specialai-1.1.0_for_mc1.12.2.jar                  | None                                     |
       | LCHIJA | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
       | LCHIJA | theoneprobe                       | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                       | None                                     |
       | LCHIJA | tramplestopper                    | 1.2.0.4                  | tramplestopper-1.12.2-1.2.0.5-universal.jar       | None                                     |
       | LCHIJA | traverse                          | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                      | None                                     |
       | LCHIJA | tropicraft                        | 7.1.9.115                | tropicraft-MC1.12.2-7.1.9.115.jar                 | None                                     |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCHIJA | vehicle                           | 0.38.0                   | vehicle-mod-0.38.0-mc1.12.2.jar                   | None                                     |
       | LCHIJA | visuals                           | 6r                       | Visuals-1.12.2-6r.jar                             | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | walljump                          | 1.12.2-1.2.3             | walljump-1.12.2-1.2.3.jar                         | None                                     |
       | LCHIJA | worldedit                         | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
       | LCHIJA | llibrary                          | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                  | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.17.1.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Quark Plugin (Quark-r1.5-168.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      HCASM (HammerCore-1.12.2-2.0.4.7.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.211.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      offlineskins (OfflineSkins-1.12.2-v5g-core.jar)
                                        lain.mods.skins.init.forge.asm.ASMTransformer
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.21.1-build.0377.jar)
                                        
                                      ApotheosisCore (Apotheosis-1.12.2-1.10.2.jar)
                                        shadows.ApotheosisTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      MMFMLCorePlugin (MultiMine-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.16-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 4793 names; 3903 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Visuals (visuals) @6r
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Offline mode for dedicated servers is NOT supported by Ender IO.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Mine and Slash (mmorpg)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 20; [GCEntityPlayerMP['Hamadawana'/102076, l='PointFourForRealSpawn', x=-548.74, y=219.00, z=-19.87]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by HamzasHere** [comment]
I guess it's a mod conflict but I have no idea with which mod. Love your mod btw :>

**Comment by RobertSkalko** [comment]
Sorry. 1.12 is no longer supported. I'll add that to my page somewhere.
