### ISSUE TITLE
[1.14.4] Every server start leads to this error -ava.lang.Exception: Unique Id doesn't exist: swordphysical0

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#52]
I see this in console every time I start a new world.
Mine and Slash-1.14.4-2.2.5

https://gist.github.com/ProsperCraft/ffb338b17473e2db3214850a7a0528a3

**Comment by RobertSkalko** [comment]
a full log could help. i'm baffled why that 1 item isn't registered.

**Comment by RobertSkalko** [comment]
btw does it crash the server or just throw the error

**Comment by RobertSkalko** [comment]
gonna upload a new version, see if it still happens

**Comment by RobertSkalko** [comment]
closing unless it happens again
