### ISSUE TITLE
[REQUEST] Option to turn off stamina requirement

### ISSUE THREAD

**Issue by TheSexyYeti** [RobertSkalko/Mine-and-Slash#53]
Is there any way I can turn off the stamina requirement for attacking. I love your mod. But I wanna have Zombie Awareness in my mod pack as well. And the mechanic where when your stamina is too low you do no damage really makes that impossible. Zombie Awareness creates swarms of creatures. And with this stamina requirement it makes facing huge numbers of enemies pretty much guaranteed death.

**Comment by RobertSkalko** [comment]
go to configs and change energy regen to a super high number. no need for another config
