### ISSUE TITLE
[1.14.4] Eggs need localizing.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#54]
![2019-07-28_22 57 15](https://user-images.githubusercontent.com/4427684/62022866-68e63a80-b18b-11e9-8525-2755c64eef17.png)

**Comment by RobertSkalko** [comment]
those are not supposed to be craftable...?

**Comment by ProsperCraft** [comment]
Nope, not missing a recipe, missing a localized name.


block.mmorpg.egg_loot_crate.

**Comment by RobertSkalko** [comment]
ooh. now that i think about it.. if you use the one probe you would use the name.. i kinda assumed cus they arent craftable they dont need a name lol. adding to todo

**Comment by RobertSkalko** [comment]
fixed in latest update
