### ISSUE TITLE
Auto Salvage Bag + Master Bag deletes every Spell

### ISSUE THREAD

**Issue by dragonriderworld** [RobertSkalko/Mine-and-Slash#55]
So I have a Common Auto Salvage Bag (->ASB) and a Master Bag. Every spell I collect gets nuked. The filter in the common ASB says "Spells: Common", so it only deletes Common Spells or am I wrong?

Every other Item works fine (Runes, Maps, RuneWords, Currency, Gear).

**Comment by RobertSkalko** [comment]
so? try give yourself a non common spell with /givespell command, drop and pick it up and see for urself

also check the spell section of the master bag, and check if you have other auto pickup bags in ur invnetory.

**Comment by dragonriderworld** [comment]
I collected spells since one hour in lvl. 20 Maps...
In the master bag Spell section is nothing.
And i have no other Auto pickup bag in my inventory.

**Comment by RobertSkalko** [comment]
use /givespell command and try with spells of all different rarities (0 to 5)

**Comment by dragonriderworld** [comment]
When i use /givespell AcidBolt 20 3 it says "unknown command here -> ...cidBolt 30 3"

**Comment by dragonriderworld** [comment]
wait i used /givespell GameofDragons AcidBolt 20 3

**Comment by dragonriderworld** [comment]
ok i have to add an amount xD sry

But when i drop the Rare Spell it gets deleted

**Comment by dragonriderworld** [comment]
![image](https://user-images.githubusercontent.com/40246719/62129208-74924800-b2d6-11e9-8833-f98dcf53ade2.png)
![image](https://user-images.githubusercontent.com/40246719/62129235-82e06400-b2d6-11e9-9919-0f717bea664b.png)

**Comment by RobertSkalko** [comment]
if u clicked the book icon in the master bag then it could be a bug.

please send me your save file if its singleplayer.

**Comment by RobertSkalko** [comment]
wait nvm. i found the bug

**Comment by dragonriderworld** [comment]
A specific folder or the whole world?

PS: i can place Spells into the masterbag manually.

**Comment by dragonriderworld** [comment]
oh ok^^

**Comment by RobertSkalko** [comment]
it was a minor bug, the new system for rarities was put in and i forgot to implement it for the spell, so it defaulted to 0 (common)..

i didnt notice as i didnt have time to play these days.. ill release a hotfix soon

**Comment by dragonriderworld** [comment]
And I wondered why I get no Spells..i got no spell since yesterday. Since 1 hour i tested around with spells i get. But every Spell got nuked xD

**Comment by dragonriderworld** [comment]
Another request: Would it be possible to add a None deltion funktion like with the bags but for everything else?

And: Sorry for my english...I'm from Germany ^^

**Comment by dragonriderworld** [comment]
Fail: meant like with the maps

**Comment by RobertSkalko** [comment]
u can set it to none i think by resseting the full config, by using nothing instead of an item

**Comment by dragonriderworld** [comment]
No then it resets to the Config I sent in my pic

**Comment by RobertSkalko** [comment]
ill check it, anyway try the new build

**Comment by dragonriderworld** [comment]
I tried it again - doesn't work...

**Comment by RobertSkalko** [comment]
https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded/files/2751417

**Comment by RobertSkalko** [comment]
i see, hm ill have to do another hotfix xD

**Comment by dragonriderworld** [comment]
xD

**Comment by dragonriderworld** [comment]
The firts issu is fixed now ^^ Yaay

**Comment by RobertSkalko** [comment]
alright closing cus its fixed
