### ISSUE TITLE
Portals are not removed when a map is closed nor when a map device is broken. 

### ISSUE THREAD

**Issue by VeloxAzo** [RobertSkalko/Mine-and-Slash#56]
I died in a permadeath map, then removed my map device and placed it one block under its original position. I now have two sets of portals as seen here. https://i.imgur.com/GbtqIwM.jpg

Entering a new map will take me to the old permadeath map about 75% of the time. I'm unsure if it uses the stats of the new or old map. 

Exiting the map at one point took me about 1,000 blocks away from my map device and put me one block into the ground. I suspect these were the coordinates for the spawn of the other map.

**Comment by VeloxAzo** [comment]
All these are submitted as one issue as I assume they're all related to the fact there are two portals right on top of each other.

**Comment by RobertSkalko** [comment]
>I died in a permadeath map, then removed my map device and placed it one block under its original position. I now have two sets of portals as seen here. https://i.imgur.com/GbtqIwM.jpg

Entering a new map will take me to the old permadeath map about 75% of the time. I'm unsure if it uses the stats of the new or old map

this is intended. break the portal blocks yourself, it's possible.

the last one seems to be an issue, open a new issue with more info if you want.

**Comment by VeloxAzo** [comment]
I should restate - I had already died in the permadeath map, therefor I should not be able to enter it again.

**Comment by RobertSkalko** [comment]
if you sacrificed a new map after dying that is intended. If you died and instantly went into the portal and still had time for a map and teleported succesfully, that's a bug, open a new issue for it.
