### ISSUE TITLE
[1.14.4] mob catching mods re-roll how rare a creature is.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#57]
https://gyazo.com/4b395f4283b26a9690f5c0e2de2bbc1f

Every time I pick up this horse and put it back down it re-rolls it.

**Comment by RobertSkalko** [comment]
if the capabilities were kept, it should keep the rarity..

**Comment by RobertSkalko** [comment]
just tested. he doesnt keep my capability for some reason. so it's almost 100% the mob catcher mod's fault.

**Comment by RobertSkalko** [comment]
iitemstack made it work, closing cus it was fixed + not my mod's issue
