### ISSUE TITLE
Exiting a map with a pearl sometimes does not return you to your map device. 

### ISSUE THREAD

**Issue by VeloxAzo** [RobertSkalko/Mine-and-Slash#58]
https://i.imgur.com/PCo71VC.png

I was returned to the overworld correctly, but I think the coordinates I was returned to are the same as what I had inside the map dimension, as the mobs are the same level. 

The pearl may have been in my inventory from a previous map.

**Comment by RobertSkalko** [comment]
Not sure, what u say suggests the location wasnt even set after the teleport.

**Comment by VeloxAzo** [comment]
Recreated this twice by being on a mount on a Lycanites ventoraptor when teleported. Both into the adventure map and out of it.

**Comment by RobertSkalko** [comment]
Does this still happen on the newest patch?

**Comment by RobertSkalko** [comment]
i'm gonna close this as it seems to be resolved (i didn't get any complaints since the update)
