### ISSUE TITLE
[1.14.4] Client crash when left clicking anything.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#59]
https://gist.github.com/ProsperCraft/d1bbd68a236d6405122fb62c94e0f0e1

**Comment by ProsperCraft** [comment]
Build: 1.14.4-28.0.34 - Fri Aug 02 20:50:19 GMT 2019
	mh:
		Fixed PlayerInteractEvents not working (#5976)

Time to remove workarounds.

**Comment by RobertSkalko** [comment]
hm i think thats cus the event now works both on server and client. ill just add a simple check

**Comment by RobertSkalko** [comment]
actually just deleted the event and made it onblockactivated in the attunement block. unsure why i made it an event in the first place. probably cus i thought the right clicks of hearthstone item and the block use would conflict, seems they dont

**Comment by LimeTheOn** [comment]
Woke up, updated forge, game crashed after trying to put out some fire "seems weird" I thought, went to report it thinking "I guess im not working on the modpacks today" just to see you already working on it and bam 10 min later fix is up. im starting today with a big smile, thank you! :D

**Comment by RobertSkalko** [comment]
closing cus seems i fixed it

**Comment by ProsperCraft** [comment]
confirmed fixed.
