### ISSUE TITLE
New version and old archive BUG

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#6]
thank you for your timely update of Unsalvagable BUG.

Today I found a new bug, but it seems that this is not a problem with this mod. I don't know how to delete it, sorry.
--------------------------------------------------------------------
I hope to add text about new content rune and set in lang, which can make the game translation better. Thanks for your mod, you and the mod are great.

My English is not very good, this comes from Google Translate.

**Comment by RobertSkalko** [comment]
Sure thing, closing both threads with the confirmation!
