### ISSUE TITLE
[v2.4.5] load error

### ISSUE THREAD

**Issue by fuzzyfungi** [RobertSkalko/Mine-and-Slash#60]
Error on load:
Mine and Slash (mmorpg) has failed to load correctly
net/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent

[latest.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3470438/latest.log)

**Comment by RobertSkalko** [comment]
downgrade ur forge version. ill release a new version that supports the new forge version as curios just updated.

**Comment by RobertSkalko** [comment]
i pushed an update if you want to play on the new forge version (but i doubt it cus other mods you play probably didnt all update yet)

**Comment by fuzzyfungi** [comment]
Added JEI v.6.0.0.8 back in (per dependencies) and crashed the application on world load but it's designated for 1.14.3.  Everything else runs fine once JEI is removed.  Much appreciated.
