### ISSUE TITLE
[BUG]1.12.2 Awaken RuneWord

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#62]
Ghost's combination VOH+XAH+BER+XAH+CEN cannot be put into 2 XAH。

http://i1.fuimg.com/542480/c8beddc06c4a59f5.png

**Comment by RobertSkalko** [comment]
1.12.2 is no longer supported sorry

**Comment by mcfensi** [comment]
This is really regrettable, the 1.12.2 server is still the current mainstream
