### ISSUE TITLE
NullPointerException: Rendering overlay

### ISSUE THREAD

**Issue by ThatBenderGuy** [RobertSkalko/Mine-and-Slash#64]
I get a crash as soon as Forge finishes loading. 
I am running forge 1.14.4 (28.0.45) and MaS version 2.4.10

Here is the crash log
[crash-2019-08-11_19.53.24-client.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/3490904/crash-2019-08-11_19.53.24-client.txt)

**Comment by RobertSkalko** [comment]
ill add more safety in next update there

**Comment by RobertSkalko** [comment]
should be fixed in latest updat,e if it happens stil, either comment or open new issue
