### ISSUE TITLE
[1.14.4] Huge stacktraces in console -  [com.robertx22.mine_and_slash.uncommon.capability.EntityCap$DefaultImpl:setNBT:332]: java.lang.IllegalArgumentException: No enum constant com.robertx22.mine_and_slash.uncommon.utilityclasses.EntityTypeUtils.EntityType.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#67]
Mine and Slash-1.14.4-2.5.0.jar

[debug.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3513283/debug.log)
[latest.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3513284/latest.log)

**Comment by RobertSkalko** [comment]
i think that's not a huge issue, i just forgot to add safety. As long as everything works that should not happen anymore much (it should happen once for each entity that's loaded, woops)

**Comment by RobertSkalko** [comment]
closing cus hotfixed
