### ISSUE TITLE
Weakness make all attack miss unless use ranged weapon

### ISSUE THREAD

**Issue by zongitgud** [RobertSkalko/Mine-and-Slash#69]
Minecraft version: 1.12.2
Mod version: latest
  Weakness debuff (which usually cause by mob) cause all melee attack whiff, ranged are unaffected. Just to be sure, i slowly disable my mods one by one, until i disable M&S i can start attack normal again. 
My target was a dragon from ice and fire, which cast weakness with it roar for roughly 1mins. I also tested by custom npc (created a mob that do weakness on hit) and a witch, same result. After further testing it seem that some weapon from dothack are unaffected. You can also applied strength buff on yourself and your attack start hitting again.

**Comment by RobertSkalko** [comment]
Will be fixed in 1.14. 1.12 is not supported. But the fix will be delayed as i'm working on a bigger update currently.

**Comment by RobertSkalko** [comment]
should be fixed, reply or open another if it's still going on in 1.14
