### ISSUE TITLE
Bag BUG

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#7]
Any bag from the Hotbar to the inventory, then from the inventory to the Hotbar, will cause the contents of the bag to disappear.

My friend’s stuff is gone, he is very sad.

Sorry, my English is not very good. I am using Google Translate. I hope you can understand.

**Comment by RobertSkalko** [comment]
Was your friend switching to creative mod? This seems to be a forge bug unfortunately.

**Comment by mcfensi** [comment]
> 您的朋友是否切换到创意模式？不幸的是，这似乎是一个伪造的错误。

Survival Mode

**Comment by RobertSkalko** [comment]
I probably can't fix this. In case someone else reports it happening in singleplayer then it's probably my problem then i'll try fix it. Sorry for the issues.
