### ISSUE TITLE
Make Vanilla weapons compatible

### ISSUE THREAD

**Issue by Ge0rgi-CR** [RobertSkalko/Mine-and-Slash#70]
Hi, you says that is a way to make vanilla weapons compatible but I couldn't find it, I just would like the mod weapons have the possibility to look like a vanilla one since I have a custom texure pack, it may be optional.

Thank you for such awesome mod!!

**Comment by RobertSkalko** [comment]
That's not what compatible items are. And no i won't be doing this Sorry. I don't have interest in supporting texture packs.
