### ISSUE TITLE
[BUG]2.6.0 open Loot Crate Client crash

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#71]
Loot Crate Right click will cause the client to crash

**Comment by RobertSkalko** [comment]
please post the crash log cus i can't reproduce it

**Comment by mcfensi** [comment]
[debug.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3568549/debug.log)

**Comment by mcfensi** [comment]
[crash-2019-09-03_16.24.17-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/3568569/crash-2019-09-03_16.24.17-server.txt)

**Comment by RobertSkalko** [comment]
I think i fixed it. I'm uploading an update. Should be there in a few minutes

**Comment by mcfensi** [comment]
Thank you

**Comment by RobertSkalko** [comment]
the weird part is.. this crash can only happen if a player of lvl 4 or less opens the loot crate. But maps dont drop bellow lvl 10. So at least this bug should be pretty rare
