### ISSUE TITLE
Mine and Slash bow shoots through blocks

### ISSUE THREAD

**Issue by Drakyl** [RobertSkalko/Mine-and-Slash#72]
Modpack:  Bane of Dragons  version 1.5.6
Modpack creater: Kreezxil
Link to pack (still in development): https://kreezcraft.com/download/bane-of-dragons-1-5-6-indev/

Issue:
Using a Mine and Slash bow with vanilla minecraft arrows allows it to shoot through blocks as if they were not there. Must be a bow acquired from mob drop or crate.

**Comment by RobertSkalko** [comment]
1.12 isn't supported. I made a sticky to note that now.

**Comment by AzureZhen** [comment]
I'm taking a look at this, to see what changes in arrows were done in 1.14 to backport.

**Comment by RobertSkalko** [comment]
I just changed it to use normal vanilla bowitem
