### ISSUE TITLE
[1.14.4]2.6.2 instability

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#75]
After the instability reaches 250, can't it continue to strengthen? Is this the setting or BUG?

Also, when the instability reaches 250, you can't use Chaos Orb.

**Comment by RobertSkalko** [comment]
That's a feature. You have limited tries to modify it.
But i could make it so chaos orb can be used even at the limit.

**Comment by mcfensi** [comment]
Okay thank you

**Comment by RobertSkalko** [comment]
You can disable it in the config if you dislike it.
