### ISSUE TITLE
Putting a tome in your hand crashes game

### ISSUE THREAD

**Issue by itsEvil** [RobertSkalko/Mine-and-Slash#78]
I created a new world with the mods, Controlling, Curios API, JEI and Mine and Slash with Forge 28.0.95 and every time i loaded the world and tried to hold the tome my game just crashed. 

Crash log
https://pastebin.com/HatLcgRH

**Comment by RobertSkalko** [comment]
Use forge v82 until i update the mod for the latest forge version

**Comment by RobertSkalko** [comment]
should be fixed in latest update
