### ISSUE TITLE
Can't heal anymore after removing mod

### ISSUE THREAD

**Issue by iMoobert** [RobertSkalko/Mine-and-Slash#80]
I removed the mod because it was making my game crash (and I can't roll back forge because of my other mods), but after I did, even with a full food/stamina bar, my health isn't going back up at all. I tried dying and checking again afterwards but that didn't fixed it.
I don't know what to do, or how I would even fix it.

When I made a new world to see if it was another mod still in use, my health regenerated just fine.

I don't want to delete my world or start fresh again :c I would appreciate any sort of insight.

Minecraft: 1.14.4
Forge: 28.0.91
Mod removed: Mine+and+Slash-1.14.4-2.6.3

**Comment by RobertSkalko** [comment]
it's a gamerule. Just do /gamerule natural regen or something

**Comment by iMoobert** [comment]
Oh wonderful! Thank you so much :D
it was /gamerule naturalRegeneration true
Are there any other gamerules the mod changed that I should know about?

**Comment by RobertSkalko** [comment]
No others. Sorry about that. Gonna close this. I think i'll enable it on server shutdown
