### ISSUE TITLE
[1.14.4] Server crash - Sidedness issue with professions when opening a crafting table.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#81]
https://gist.github.com/ProsperCraft/477973f5f81083d12a5ed029cee84f26

forge-1.14.4-28.1.7
Mine and Slash-1.14.4-2.7.2

Reproduced here-
https://paste.fedoraproject.org/paste/AUaYUG-94ip5D5qRkH5e~A

A Player who has not chosen a profession yet makes the server crash when opening the tinkering station.

**Comment by RobertSkalko** [comment]
should be fixed
