### ISSUE TITLE
[1.14.4] Server crash - Attempted to load class net/minecraft/client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by pandory-network** [RobertSkalko/Mine-and-Slash#84]
**Mine and Slash Version:** Mine and Slash-1.14.4-2.8.0 and Mine and Slash-1.14.4-2.8.1
**Forge Version:** 1.14.4-28.1.10

**Error:**

> [22Sep2019 09:46:38.338] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: mmorpg, class com.robertx22.mine_and_slash.mmorpg.MMORPG
> java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER

[2019-09-22-7.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3639474/2019-09-22-7.log)
[debug-5.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3639475/debug-5.log)

**Comment by RobertSkalko** [comment]
thanks, this tends to happen to me a lot heh, sec

**Comment by RobertSkalko** [comment]
try with new build, should upload in a few mins

**Comment by pandory-network** [comment]
I have Test it, the old Error are Solved now i the Server Crashed with error message

> Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

Here the current Crash Report
[crash-2019-09-22_11.04.12-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/3639541/crash-2019-09-22_11.04.12-server.txt)

**Comment by RobertSkalko** [comment]
up in a few mins, that one should be fixed too

**Comment by pandory-network** [comment]
The server starts now without error.
Thanks for the quick support and for the mod itself.

> Offtopic: I'm currently in the process of translating the mod. In the German language. Will the days to publish a pull request.

**Comment by RobertSkalko** [comment]
Np, closing cus fixed. Appreciate the translation too
