### ISSUE TITLE
[1.14.4]XP LOSS ON DEATH

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#86]
When experience overflows, such as 200/92, it will become 92/92 after death.

**Comment by RobertSkalko** [comment]
What's the bug? I introduced xp loss on death recently

**Comment by mcfensi** [comment]
The experience value of the overflow will become the upper limit, such as 2000/92, and will become 92/92 after death. is this normal?

**Comment by RobertSkalko** [comment]
ah i see, ye i did clamp the xp down forgetting that exists. Still not sure how that should work but ill just fix it for next patch

**Comment by mcfensi** [comment]
thank you
