### ISSUE TITLE
[Shaders] 1.12.2-1.14.4 The problem with the health bar and shaders

### ISSUE THREAD

**Issue by LexArk54** [RobertSkalko/Mine-and-Slash#89]
The health bar above the mobs becomes transparent when using shaders.

Shaders OFF
![image](https://user-images.githubusercontent.com/31623633/65937463-a637a480-e428-11e9-98e3-0d999dbd7fbe.png)

Chocapic13 v6 Ultra
![image](https://user-images.githubusercontent.com/31623633/65937307-2ad5f300-e428-11e9-9a01-3d0678bfc091.png)

SEUS PTGI E6
![image](https://user-images.githubusercontent.com/31623633/65937430-830cf500-e428-11e9-923b-bebd4e99cd69.png)

**Comment by RobertSkalko** [comment]
Does the same happen if you use neat mod's gui instead of mine? Cus i just took neat's code and adjusted the hp values. Maybe he fixed it in 1.14 port

**Comment by LexArk54** [comment]
Yes, this is a neat mod problem. 

Disabled VBO - the background appeared on the Chocapic13 v6 shader, but when looking at the sky - it disappears completely. Sorry for the inconvenience, the problem is not yours.
![image](https://user-images.githubusercontent.com/31623633/65954841-794ab800-e44f-11e9-8ae9-64c1f43c9dc1.png)

Та же проблема наблюдается у waypoints Xaero's Minimap.
Противный OptiFine...
![image](https://user-images.githubusercontent.com/31623633/65954895-a13a1b80-e44f-11e9-889c-ba941525f592.png)

**Comment by RobertSkalko** [comment]
Np, you'll have more luck reporting it to neat. Closing.
