### ISSUE TITLE
Gear Craft Station and Capacitor BUG

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#9]
Capacitor is used in Gear Craft Station and will disappear。

Sorry, my English is not good. This is from Google Translate. I hope you can understand it.

**Comment by RobertSkalko** [comment]
Thanks, will check it out.

**Comment by AzureZhen** [comment]
I found how to reproduce the issue, place a Capacitor in the top slot during the crafting stage and when it's completed, it's gone.
