### ISSUE TITLE
[1.12.2] Map Crashing (Biome Detection Error?)

### ISSUE THREAD

**Issue by Lanphrost** [RobertSkalko/Mine-and-Slash#91]
I'm currently having an issue with the 1.12.2 version of Mine and Slash in which map generation often causes a crash and when I log back in the map is consumed and nothing has changed.

The crash log is here, https://paste.dimdev.org/dalenuyuti.mccrash
but it doesn't get to the root of the issue, which I believe I have. Maps that are beyond doubt vanilla biomes work, such as red dessert and spruce forest, but other maps appear to be biomes from Biomes o' plenty, and those are the ones that will definitely crash each time. I've tried installing BoP to alleviate the issue, but even when not in a BoP world it puts so much additional strain on my game that I can't keep playing. I haven't made it back to my base to test the maps and see if this is truly the solution or not.

**Comment by Lanphrost** [comment]
Whelp, BoP didn't fix it. Dunno what's going on. It's kinda sad because maps is probably what I was most excited for. Either way, thank you both for all the work you're putting in and if you can figure out what I've broken it's probably user error somewhere along the line.

**Comment by RobertSkalko** [comment]
closing as 1.12 is being retired
