### ISSUE TITLE
[1.14.4] Learn a Talent Crashes Dedicate Server

### ISSUE THREAD

**Issue by pandory-network** [RobertSkalko/Mine-and-Slash#94]
When I select a Telent and click this, the Dedicated Server crashes.

**Error:**

> `[11Oct2019 15:30:47.813] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
> java.lang.NoSuchMethodError: net.minecraft.network.PacketBuffer.func_218666_n()Ljava/lang/String;
> 	at com.robertx22.mine_and_slash.network.AllocateTalentPacket.decode(AllocateTalentPacket.java:33) ~[?:1.14.4-2.9.0]
> 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:106) ~[?:?]
> 	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_222]
> 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:106) ~[?:?]
> 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:147) ~[?:?]
> 	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:65) ~[?:?]
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
> 	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:82) ~[?:?]
> 	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?]
> 	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_222]
> 	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?]
> 	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1275) ~[?:?]
> 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
> 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
> 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
> 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
> 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

**I use the following versions:**
Mod Version: Mine+and+Slash-1.14.4-2.9.0
Forge Version: forge-1.14.4-28.1.44

**Debug Log:**
[debug-1.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3717810/debug-1.log)

**Log:**
[2019-10-11-3.log](https://github.com/RobertSkalko/Mine-and-Slash/files/3717813/2019-10-11-3.log)

**CrashLog:** 
[crash-2019-10-11_15.30.47-server.txt](https://github.com/RobertSkalko/Mine-and-Slash/files/3717828/crash-2019-10-11_15.30.47-server.txt)

**Comment by RobertSkalko** [comment]
pushing a hotfix

**Comment by pandory-network** [comment]
Bug is fixed, Server works. Thx for the fast support
