### ISSUE TITLE
[1.14.4] Render Error Spam in log

### ISSUE THREAD

**Issue by TheCallunxz** [RobertSkalko/Mine-and-Slash#95]
`[11Oct2019 23:50:58.400] [Client thread/ERROR] [net.minecraft.client.MainWindow/]: ########## GL ERROR ##########
[11Oct2019 23:50:58.400] [Client thread/ERROR] [net.minecraft.client.MainWindow/]: @ Render
[11Oct2019 23:50:58.401] [Client thread/ERROR] [net.minecraft.client.MainWindow/]: 65539: Invalid key 0`

Getting this spammed in the log constantly and its causing spikes of lag

**Comment by RobertSkalko** [comment]
is that it from the log? does the error go away if you have all gear that meets requirements? (no icons on middle right of screen?)

**Comment by TheCallunxz** [comment]
https://pastebin.com/8c7RMbTW

This is the entire log from the "latest" file. I don't have any gear on and I'm not holding gear, newly generated world with spawn with items set to false.

**Comment by RobertSkalko** [comment]
I'm kinda clueless, so as a precaution, make sure you're getting this error with just my mod and curios. And make sure you aren't using optifine

**Comment by TheCallunxz** [comment]
Yeah, I originally did have it in a modpack. But I stripped everything else away and it still happens with just the mod and curios.

**Comment by RobertSkalko** [comment]
asked giga and he didn't solve it either. Last thing i can think of, does it stop if you disable hp renderers? 

There's a Disable Neat Overlay keybind. You have to bind it.

**Comment by TheCallunxz** [comment]
Looks like binding the key fixed it, seems like its caused by binding the key to a key which doesnt exist. So it bugs out and can't render the correct key name. Idk, but binding the key and disabling then renabling fixed it. Not sure why lol

**Comment by TheCallunxz** [comment]
Yep, resetting the key to the strange key it was set to brings back the rendering error. I guess just default the key to something

**Comment by RobertSkalko** [comment]
keybindings shouldnt be the problem. im just asking if the error happens when u disable the neat renderer with the keybind.

**Comment by TheCallunxz** [comment]
Yes I know what you were asking :P. But you managed to find the issue accidentally. The issue was you set the key binding to integer 0. Minecraft was trying to render that and for some reason it didnt like it. When I change the key binding to anything else it doesnt spam the GL error. But if I reset the keybinding back to what it [was](https://gyazo.com/8d14ebf226ee361a4f884e5fb0ecdc18) the GL errors are once again messaged frequently in the logs.

**Comment by TheCallunxz** [comment]
Also seems like when the keybinding is set 0. The error comes up when I open my inventory or any gui

**Comment by RobertSkalko** [comment]
Wow are you kidding me. I thought you were confused.. Great if it's true! I'll change the keybinding in next update.

**Comment by TheCallunxz** [comment]
giga has this line in his toolbelt mod: 
`new KeyBinding("key.toolbelt.cycle.left", -1, "key.toolbelt.category"));`
Which is why his error is -1 and yours is 0. 
The issue is with the keybindings.

**Comment by RobertSkalko** [comment]
This is amazing
