### ISSUE TITLE
[1.14.4] Major inbalance in energy requirement to swing a hammer.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#97]
I am level 17 and I can only swing my level 10 hammer four times and I have 11 stam

![2019-10-12_19 41 41](https://user-images.githubusercontent.com/4427684/66709809-d33d5e80-ed28-11e9-8ffb-d3dbb09a9aea.png)

Drem's hammer went up to costing 783 energy.  It is level 30.  He is level 36 and has 150 energy so can't swing his hammer even once.

Mine and Slash-1.14.4-2.9.2

**Comment by ProsperCraft** [comment]
Might be all gear costing too much energy actually.

**Comment by ProsperCraft** [comment]
My heal spell takes more mana then I have and it is six levels below me.

**Comment by ProsperCraft** [comment]
using my wand says it takes 21 mana but it actually takes 100, I think there is a math error somewhere.

**Comment by RobertSkalko** [comment]
reset your stat configs in mmorpg common. you're supposed to have way more energy
