### ISSUE TITLE
Improvement Health over 1000 Version Irrelevent

### ISSUE THREAD

**Issue by Drunkender** [RobertSkalko/Mine-and-Slash#98]
On the mod page you stated that you do something weird to use health over 1000.

I don't know if this is still relevant but.

Have you thought about using [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix) to bypass this. The default Max attributes are 6k but can be increased to MAX_INT in the config.

**Comment by RobertSkalko** [comment]
I did, but then other things like fall dmg wouldn't matter at all. I feel this was the better choice.
