### ISSUE TITLE
[1.14.4]Single Player Adventure Map

### ISSUE THREAD

**Issue by mcfensi** [RobertSkalko/Mine-and-Slash#99]
**1**
Single-player game, after the map expires, you can still use the same type of map to return to the previous adventure map. The map cannot reset the world in the adventure map, and you can still return to the previously constructed adventure map with the same world type, unless Restart the game to reset. 

**2**
The adventure map data of the single player game will be stored indefinitely and the file data will be too large.

**3**
In addition to the 2.9.2 crit stream talent is too Over Power, you can spike any monster.

**Comment by RobertSkalko** [comment]
1 is not a bug. 2 is false, all maps are deleted on reset.

What is crit stream?

**Comment by mcfensi** [comment]
3 Seems like critical hit
